package webui

const agentConfigTemplate = `
{{define "agent-config-page"}}{{$page := .AgentConfigPage}}{{$server := $page.Server}}{{$runtime := index $page.Agent.Runtime $page.Catalog.Engine}}
  <section class="node-config-source config-command-bar {{if $page.SourceDraft}}loaded{{end}}" {{if and (not $page.SourceDraft) (not $.FocusTaskID)}}role="status" aria-live="polite"{{end}}>
    <header class="config-command-head">
      <div class="config-command-title"><span class="engine-badge {{$page.Catalog.Engine}}">{{$page.Catalog.Name}}</span><span><h2>{{$server.Selected.Name}}{{if $server.Editing}} · {{$server.OriginalTag}}{{else}} · 新入站{{end}}</h2>{{if ne $page.Agent.Status "online"}}<small>节点离线</small>{{else if not $runtime.Installed}}<small>未安装内核</small>{{end}}</span></div>
      <div class="config-command-state"><span class="status-label {{if $page.SourceDraft}}ok{{else}}warn{{end}}">{{if $page.SourceDraft}}已读取{{else if or (ne $page.Agent.Status "online") (not $runtime.Installed)}}不可用{{else}}读取中{{end}}</span><span class="recipe-version"><b>{{if $page.HasSavedConfig}}v{{$page.Config.Version}}{{else}}草稿{{end}}</b><small>{{$page.Catalog.Format}}</small></span><a href="{{$server.Selected.Docs}}" target="_blank" rel="noopener noreferrer">文档 ↗</a></div>
      {{if and (not $page.SourceDraft) (eq $page.Agent.Status "online") $runtime.Installed (not $.FocusTaskID)}}<form method="post" action="/ui/tasks" data-auto-read-current hidden><input type="hidden" name="csrf" value="{{$.CSRF}}"><input type="hidden" name="agent_id" value="{{$page.Agent.ID}}"><input type="hidden" name="engine" value="{{$page.Catalog.Engine}}"><input type="hidden" name="action" value="read-config"><input type="hidden" name="automatic_read" value="1"><input type="hidden" name="return_to" value="{{$page.ReturnTo}}"></form>{{end}}
    </header>
    <details class="config-hierarchy-menu" open>
      <summary><b>切换入站 / 协议</b><i>＋</i></summary>
      <div class="config-command-selectors">
        {{if $server.Inbounds}}<section class="inbound-browser config-selector"><header><span><b>入站</b><small>{{len $server.Inbounds}} 个</small></span>{{if ne $page.Catalog.Engine "ss-rust"}}<a class="button small" href="/agents/{{$page.Agent.ID}}/config/{{$page.Catalog.Engine}}?protocol={{$server.Selected.Key}}&regenerate=1{{if $page.SourceDraft}}&source_task={{urlquery $page.SourceTaskID}}{{end}}">＋ 新增</a>{{end}}</header><nav>{{range $server.Inbounds}}<a class="{{if eq .Tag $server.OriginalTag}}active{{end}}" href="/agents/{{$page.Agent.ID}}/config/{{$page.Catalog.Engine}}?protocol={{.Protocol}}&inbound={{urlquery .Tag}}{{if $page.SourceDraft}}&source_task={{urlquery $page.SourceTaskID}}{{end}}"><span><strong>{{.Tag}}</strong><small>{{.Listen}}:{{.Port}}</small></span></a>{{end}}</nav></section>{{end}}
        <section class="protocol-browser config-selector"><header><span><b>协议</b><small>{{len $server.Protocols}} 种</small></span></header><nav>{{range $server.Protocols}}<a class="{{if eq .Key $server.Selected.Key}}active{{end}}" href="/agents/{{$page.Agent.ID}}/config/{{$page.Catalog.Engine}}?protocol={{.Key}}{{if $page.SourceDraft}}&source_task={{urlquery $page.SourceTaskID}}{{end}}"><b>{{.Badge}}</b><span><strong>{{.Name}}</strong></span></a>{{end}}</nav></section>
      </div>
    </details>
  </section>

  <article class="recipe-workspace">
    <form class="server-form" method="post" action="/ui/agents/{{$page.Agent.ID}}/config/{{$page.Catalog.Engine}}/save">
      <input type="hidden" name="csrf" value="{{$.CSRF}}"><input type="hidden" name="mode" value="server"><input type="hidden" name="protocol" value="{{$server.Input.Protocol}}"><input type="hidden" name="version" value="{{$page.Config.Version}}">{{if $page.SourceDraft}}<input type="hidden" name="source_task" value="{{$page.SourceTaskID}}">{{end}}<input type="hidden" name="original_tag" value="{{$server.OriginalTag}}"><input type="hidden" name="name" value="{{$page.Config.Name}}"><input type="hidden" name="description" value="{{$server.Selected.Name}} 服务端入站，由 QControlHub 方案生成">

      <div class="config-mutation"><label>操作<select name="mutation">{{if $server.Editing}}<option value="modify" {{if eq $server.Mutation "modify"}}selected{{end}}>修改 · {{$server.OriginalTag}}</option>{{end}}{{if or (not $server.Editing) (ne $page.Catalog.Engine "ss-rust")}}<option value="add" {{if eq $server.Mutation "add"}}selected{{end}}>新增入站</option>{{end}}{{if $server.Editing}}<option value="delete" {{if eq $server.Mutation "delete"}}selected{{end}}>删除 · {{$server.OriginalTag}}</option>{{end}}</select></label></div>

      <div class="builder-layout" data-builder-workbench><nav class="builder-index" aria-label="参数菜单" role="tablist"><a href="#listen" data-builder-step="listen"><b>01</b><strong>监听</strong></a><a href="#identity" data-builder-step="identity"><b>02</b><strong>认证</strong></a>{{if $server.Selected.TransportConfig}}<a href="#transport" data-builder-step="transport"><b>03</b><strong>传输</strong></a>{{end}}{{if or $server.Selected.UsesReality $server.Selected.SupportsTLS}}<a href="#security" data-builder-step="security"><b>04</b><strong>安全</strong></a>{{end}}</nav><div class="builder-sections">

      <section class="builder-section" id="listen"><header><span class="section-number">01</span><strong>监听</strong></header><div class="plan-fields three"><label>入站标签<input name="tag" maxlength="64" required value="{{$server.Input.Tag}}"></label><label>监听地址<input name="listen" required value="{{$server.Input.Listen}}"></label><label>监听端口<input type="number" name="port" min="1" max="65535" required value="{{$server.PortValue}}"></label></div></section>

      <section class="builder-section" id="identity"><header><span class="section-number">02</span><strong>认证</strong></header><div><div class="plan-fields two">{{if $server.Selected.IgnoresUsername}}<input type="hidden" name="username" value="default">{{else}}<label>用户名或备注<input name="username" maxlength="64" required value="{{$server.Input.Username}}"></label>{{end}}<label class="secret-input">{{$server.Selected.Credential}}<span class="secret-value-control"><input type="password" name="credential" autocomplete="off" spellcheck="false" required value="{{$server.Input.Credential}}"><button type="button" data-secret-visibility data-secret-label="{{$server.Selected.Credential}}" aria-label="显示{{$server.Selected.Credential}}">显示</button></span></label>{{if $server.Selected.SecondaryCredential}}<label class="secret-input">{{$server.Selected.SecondaryCredential}}<span class="secret-value-control"><input type="password" name="secondary_credential" autocomplete="off" spellcheck="false" required value="{{$server.Input.SecondaryCredential}}"><button type="button" data-secret-visibility data-secret-label="{{$server.Selected.SecondaryCredential}}" aria-label="显示{{$server.Selected.SecondaryCredential}}">显示</button></span></label>{{else}}<input type="hidden" name="secondary_credential" value="">{{end}}</div>{{if $server.Selected.Methods}}<div class="plan-fields one"><label>加密方式<select name="method">{{range $server.Selected.Methods}}<option value="{{.}}" {{if eq . $server.Input.Method}}selected{{end}}>{{.}}</option>{{end}}</select></label></div>{{else}}<input type="hidden" name="method" value="">{{end}}{{if $server.Selected.UsesReality}}<input type="hidden" name="flow" value="xtls-rprx-vision"><div class="plan-fields one"><label>VLESS Flow<input value="xtls-rprx-vision" disabled></label></div>{{else}}<input type="hidden" name="flow" value="">{{end}}</div></section>

      {{if $server.Selected.TransportConfig}}<section class="builder-section" id="transport"><header><span class="section-number">03</span><strong>传输</strong></header><div class="plan-fields two"><label>传输<select name="transport">{{range $server.Selected.Transports}}<option value="{{.}}" {{if eq . $server.Input.Transport}}selected{{end}}>{{if eq . "raw"}}Raw / TCP{{else if eq . "websocket"}}WebSocket{{else}}gRPC{{end}}</option>{{end}}</select></label><label>路径 / ServiceName<input name="transport_path" value="{{$server.Input.TransportPath}}"></label></div></section>{{else}}<input type="hidden" name="transport" value="raw"><input type="hidden" name="transport_path" value="">{{end}}

      {{if $server.Selected.UsesReality}}
      <input type="hidden" name="reality_enabled" value="1"><input type="hidden" name="tls_enabled" value="0"><input type="hidden" name="certificate_path" value=""><input type="hidden" name="private_key_path" value="">
      <section class="builder-section security-section" id="security"><header><span class="section-number">04</span><strong>Reality</strong></header><div><div class="plan-fields two"><label>目标域名 / ServerName<input name="reality_server_name" list="reality-sni-presets" required value="{{$server.Input.RealityServerName}}"><datalist id="reality-sni-presets">{{range $server.RealityPreset}}<option value="{{.}}">{{end}}</datalist><small>校验公网 DNS；拒绝 Cloudflare 与非公网地址。</small></label><label>Short ID<input name="reality_short_id" required value="{{$server.Input.RealityShortID}}"></label></div><div class="plan-fields one"><label>客户端 Public Key<input name="reality_public_key" required value="{{$server.Input.RealityPublicKey}}"></label><label class="secret-input">服务端 Private Key<span class="secret-value-control"><input type="password" name="reality_private_key" autocomplete="off" spellcheck="false" required value="{{$server.Input.RealityPrivateKey}}"><button type="button" data-secret-visibility data-secret-label="服务端 Private Key" aria-label="显示服务端 Private Key">显示</button></span></label></div></div></section>
      {{else}}
      <input type="hidden" name="reality_enabled" value="0"><input type="hidden" name="reality_private_key" value=""><input type="hidden" name="reality_public_key" value=""><input type="hidden" name="reality_short_id" value=""><input type="hidden" name="reality_server_name" value="">
      {{if $server.Selected.SupportsTLS}}<section class="builder-section security-section" id="security"><header><span class="section-number">04</span><strong>TLS</strong></header><div>{{if $server.Selected.RequiresTLS}}<input type="hidden" name="tls_enabled" value="1">{{end}}<label class="tls-switch"><input type="checkbox" name="tls_enabled" value="1" {{if or $server.Input.TLSEnabled $server.Selected.RequiresTLS}}checked{{end}} {{if $server.Selected.RequiresTLS}}disabled{{end}}><strong>{{if $server.Selected.RequiresTLS}}TLS{{else}}启用 TLS{{end}}</strong></label><div class="plan-fields two"><label>证书路径<input name="certificate_path" value="{{$server.Input.CertificatePath}}"></label><label>私钥路径<input name="private_key_path" value="{{$server.Input.PrivateKeyPath}}"></label></div><p class="validation-note">私钥仅目标内核服务组可读。</p></div></section>{{else}}<input type="hidden" name="tls_enabled" value="0"><input type="hidden" name="certificate_path" value=""><input type="hidden" name="private_key_path" value="">{{end}}
      {{end}}

      </div></div>
      <footer class="builder-actions compact"><div><a class="button" href="/agents/{{$page.Agent.ID}}/config/{{$page.Catalog.Engine}}?protocol={{$server.Selected.Key}}&regenerate=1{{if $server.Editing}}&inbound={{urlquery $server.OriginalTag}}{{end}}{{if $page.SourceDraft}}&source_task={{urlquery $page.SourceTaskID}}{{end}}">重新生成参数</a><button class="button" name="intent" value="validate" type="submit" {{if ne $page.Agent.Status "online"}}disabled{{end}}>保存并校验</button><button class="button primary" name="intent" value="deploy" type="submit" data-confirm-submit="确定保存当前变更、写入节点并重启 {{engineName $page.Catalog.Engine}} 服务？" data-confirm-label="保存并部署" {{if ne $page.Agent.Status "online"}}disabled{{end}}>保存并部署</button></div></footer>
    </form>
  </article>

  {{if $page.HasSavedConfig}}
  <details class="revision-timeline node-revision-timeline" id="revisions" {{if $page.HasRevisionPreview}}open{{end}}><summary><b>版本历史</b><strong>{{len $page.Revisions}} 个版本</strong></summary><div class="timeline-body"><nav aria-label="节点配置历史">{{range $page.Revisions}}<a class="{{if and $page.HasRevisionPreview (eq .Version $page.RevisionPreview.Version)}}active{{end}} {{if eq .Version $page.Config.Version}}current{{end}}" href="/agents/{{$page.Agent.ID}}/config/{{$page.Catalog.Engine}}?protocol={{$server.Selected.Key}}{{if $server.Editing}}&inbound={{urlquery $server.OriginalTag}}{{end}}&revision={{.Version}}{{if $page.SourceDraft}}&source_task={{urlquery $page.SourceTaskID}}{{end}}#revisions"><i></i><span><b>v{{.Version}}</b><strong>{{.Name}}</strong><small>{{ago .UpdatedAt}}{{if eq .Version $page.Config.Version}} · 当前{{end}}</small></span></a>{{end}}</nav>{{if $page.HasRevisionPreview}}<section class="timeline-preview"><header><div><b>v{{$page.RevisionPreview.Version}} · {{$page.RevisionPreview.Name}}</b><small>{{engineName $page.RevisionPreview.Engine}} · {{clock $page.RevisionPreview.UpdatedAt}}</small></div>{{if eq $page.RevisionPreview.Version $page.Config.Version}}<span class="status-label ok">当前版本</span>{{end}}</header><textarea readonly aria-label="v{{$page.RevisionPreview.Version}} 节点配置正文">{{$page.RevisionPreview.Content}}</textarea>{{if ne $page.RevisionPreview.Version $page.Config.Version}}<form method="post" action="/ui/configs/{{$page.Config.ID}}/revisions/{{$page.RevisionPreview.Version}}/restore" data-confirm="确定以 v{{$page.RevisionPreview.Version}} 的内容创建一个新节点配置版本？"><input type="hidden" name="csrf" value="{{$.CSRF}}"><input type="hidden" name="expected_version" value="{{$page.Config.Version}}"><input type="hidden" name="return_to" value="/agents/{{$page.Agent.ID}}/config/{{$page.Catalog.Engine}}?protocol={{$server.Selected.Key}}{{if $server.Editing}}&inbound={{urlquery $server.OriginalTag}}{{end}}&revision={{$page.RevisionPreview.Version}}#revisions"><button class="button" type="submit">以此版本创建新版本</button></form>{{end}}</section>{{else}}<div class="timeline-placeholder">选择版本</div>{{end}}</div></details>
  {{end}}

  <details class="advanced-studio" id="advanced"><summary><b>全局字段与源码</b><i>＋</i></summary><div class="advanced-studio-body">
    <nav class="field-rail" aria-label="全局配置项"><header><b>全局配置项</b><small>{{len $page.Fields}}</small></header>{{range $page.Fields}}<a class="{{if .Selected}}active{{end}}" href="/agents/{{$page.Agent.ID}}/config/{{$page.Catalog.Engine}}?key={{.Key}}{{if $page.SourceDraft}}&source_task={{urlquery $page.SourceTaskID}}{{end}}#advanced"><i class="{{if .Present}}present{{end}}"></i><span><strong>{{.Label}}</strong><code>{{.Key}}</code></span><small>{{.Kind}}</small></a>{{end}}</nav>
    <section class="field-canvas"><header><div><h2>{{$page.Selected.Label}}</h2><code>{{$page.Selected.Key}}</code></div><a href="{{$page.Selected.Docs}}" target="_blank" rel="noopener noreferrer">文档 ↗</a></header><form method="post" action="/ui/agents/{{$page.Agent.ID}}/config/{{$page.Catalog.Engine}}/save"><input type="hidden" name="csrf" value="{{$.CSRF}}"><input type="hidden" name="mode" value="field"><input type="hidden" name="key" value="{{$page.Selected.Key}}"><input type="hidden" name="version" value="{{$page.Config.Version}}">{{if $page.SourceDraft}}<input type="hidden" name="source_task" value="{{$page.SourceTaskID}}">{{end}}<input type="hidden" name="name" value="{{$page.Config.Name}}"><input type="hidden" name="description" value="{{$page.Config.Description}}"><div class="field-mutation"><label>操作<select name="mutation">{{if $page.FieldPresent}}<option value="modify">修改字段</option><option value="delete">删除字段</option>{{else}}<option value="add">新增字段</option>{{end}}</select></label></div><label>{{$page.Catalog.Format}} 字段值<textarea name="fragment" spellcheck="false">{{$page.Fragment}}</textarea></label><footer><div><button class="button" name="intent" value="validate" {{if ne $page.Agent.Status "online"}}disabled{{end}}>保存并校验</button><button class="button primary" name="intent" value="deploy" {{if ne $page.Agent.Status "online"}}disabled{{end}}>保存并部署</button></div></footer></form><details class="source-studio"><summary>完整源码</summary><form method="post" action="/ui/agents/{{$page.Agent.ID}}/config/{{$page.Catalog.Engine}}/save"><input type="hidden" name="csrf" value="{{$.CSRF}}"><input type="hidden" name="mode" value="source"><input type="hidden" name="key" value="{{$page.Selected.Key}}"><input type="hidden" name="version" value="{{$page.Config.Version}}">{{if $page.SourceDraft}}<input type="hidden" name="source_task" value="{{$page.SourceTaskID}}">{{end}}<div class="form-grid"><label>配置名称<input name="name" maxlength="100" required value="{{$page.Config.Name}}"></label><label>说明<input name="description" maxlength="300" value="{{$page.Config.Description}}"></label></div><textarea name="content" spellcheck="false" required>{{$page.Config.Content}}</textarea><footer><div><button class="button" name="intent" value="validate" {{if ne $page.Agent.Status "online"}}disabled{{end}}>保存源码并校验</button><button class="button primary" name="intent" value="deploy" {{if ne $page.Agent.Status "online"}}disabled{{end}}>保存源码并部署</button></div></footer></form></details></section>
    <aside class="official-rail"><header><b>官方文档</b><small>{{$page.Catalog.TopicCount}}</small></header>{{range $page.Catalog.TopicGroups}}<details><summary>{{.Name}} <b>{{len .Topics}}</b></summary><div>{{range .Topics}}<a href="{{.Docs}}" target="_blank" rel="noopener noreferrer">{{.Label}} ↗</a>{{end}}</div></details>{{end}}</aside>
  </div></details>
{{end}}
`
