import { assert, waitFor } from "./assertions.mjs";
import { accountStorage } from "../modules/account-storage.js";

export async function testLargeLogRuntime({ testAPI }) {
await waitFor(() => document.querySelector(".desktop-app"), "initial shell missing");
  let releaseAgents;
  testAPI.agentsGate = new Promise((resolve) => { releaseAgents = resolve; });
  const began = performance.now();
  location.hash = "#core-logs";
  await waitFor(() => document.querySelectorAll(".core-log-row").length === 200, "default log page missing");
  assert.match(document.querySelector(".core-log-status").textContent, /已加载 4000 条/);
  const initial = performance.now() - began;
  testAPI.agentsGate = null;
  releaseAgents();
  document.querySelector("[data-toggle-core-log-refresh]").click();
  const selectedAt = performance.now();
  const limit = document.querySelector('#core-log-filters select[name="limit"]');
  limit.value = "2000";
  limit.dispatchEvent(new Event("change", { bubbles: true }));
  await waitFor(() => document.querySelector(".core-log-status")?.textContent.includes("已加载 8000 条"), "2000/engine result missing");
  const expanded = performance.now() - selectedAt;
  assert.equal(document.querySelectorAll(".core-log-row").length, 200, "8000 entries must not create 8000 DOM rows");
  assert.equal(document.querySelector(".core-log-stream .core-log-pagination"), null, "pagination must not split headings and log rows");
  assert.equal(document.querySelectorAll(".core-log-result-toolbar .core-log-pagination, .core-log-result-footer .core-log-pagination").length, 2);
  const toolbarBox = document.querySelector(".core-log-result-toolbar .core-log-pagination").getBoundingClientRect();
  const streamBox = document.querySelector(".core-log-stream").getBoundingClientRect();
  assert.ok(toolbarBox.bottom <= streamBox.top && Math.abs(toolbarBox.right - streamBox.right) < 10, "top pagination must sit outside and align with the table's right edge");
  const reads = testAPI.calls.filter((call) => call.path === "/core-logs").length;
  const pageAt = performance.now();
  document.querySelector('[data-core-log-page-index="1"]').click();
  await waitFor(() => document.querySelector(".core-log-pagination")?.textContent.includes("第 2 / 40 页"), "second page missing");
  assert.match(document.querySelector(".core-log-row pre").textContent, /entry 200/);
  const pageTime = performance.now() - pageAt;
  const filterAt = performance.now();
  const search = document.querySelector('#core-log-filters input[name="q"]');
  search.value = "pressure entry 1999";
  search.dispatchEvent(new Event("input", { bubbles: true }));
  await waitFor(() => document.querySelectorAll(".core-log-row").length === 4, "filter must search beyond the displayed page");
  const filterTime = performance.now() - filterAt;
  assert.equal(testAPI.calls.filter((call) => call.path === "/core-logs").length, reads, "local pagination/filtering must not query the remote database");
  document.querySelector("[data-reset-core-logs]").click();
  const gated = () => {
    let resolve;
    const promise = new Promise((yes) => { resolve = yes; });
    return { promise, resolve };
  };
  const preview = gated(), full = gated();
  testAPI.logGates = { "bravo:200": preview.promise, "bravo:2000": full.promise };
  const switchAt = performance.now();
  document.querySelector('[data-core-log-agent="bravo"]').click();
  assert.ok(document.querySelector('[data-core-log-agent="bravo"]').classList.contains("active"), "sidebar selection must update before network completion");
  assert.equal(document.querySelectorAll(".core-log-row").length, 0, "old node's logs must disappear immediately");
  const acknowledgement = performance.now() - switchAt;
  const previewAt = performance.now();
  preview.resolve();
  await waitFor(() => document.querySelector(".core-log-status")?.textContent.includes("已加载 800 条"), "node preview did not render before full window");
  const previewTime = performance.now() - previewAt;
  assert.match(document.querySelector(".core-log-row pre").textContent, /bravo/);
  assert.match(document.querySelector("[data-core-log-refresh-label]").textContent, /正在补齐/);
  full.resolve();
  await waitFor(() => document.querySelector(".core-log-status")?.textContent.includes("已加载 8000 条"), "node's requested window was truncated");
  document.querySelector('[data-core-log-agent=""]').click();
  await waitFor(() => document.querySelector(".core-log-row pre")?.textContent.includes("alpha"), "return to all logs failed");
  const refreshGate = gated();
  testAPI.logGates["bravo:2000"] = refreshGate.promise;
  const cachedAt = performance.now();
  document.querySelector('[data-core-log-agent="bravo"]').click();
  assert.match(document.querySelector(".core-log-row pre").textContent, /bravo/, "cached node must appear synchronously with a pending network refresh");
  assert.match(document.querySelector("[data-core-log-refresh-label]").textContent, /已显示缓存/);
  const cachedTime = performance.now() - cachedAt;
  refreshGate.resolve();
  await waitFor(() => document.querySelector("[data-core-log-refresh-label]")?.textContent === "自动更新已暂停", "cache revalidation did not settle");
  const storedPreference = JSON.parse(accountStorage.getItem("qcontrolhub:core-log-preferences"));
  assert.equal(storedPreference.agent_id, "bravo", "the selected node must be remembered");
  assert.equal(storedPreference.limit, 2000, "the expanded per-engine window must be remembered");
  assert.equal(storedPreference.auto_refresh, false, "a paused live stream must be remembered");
  assert.equal("engine" in storedPreference || "level" in storedPreference || "q" in storedPreference, false, "cleared local filters must not be remembered");
  assert.ok(initial < 5000 && expanded < 5000 && pageTime < 2000 && filterTime < 2000, "large log UI exceeded smoke responsiveness budget");
  assert.ok(acknowledgement < 500 && previewTime < 1000 && cachedTime < 500, "node switch exceeded local rendering budget");
  window.logPressureResult = { loaded: 8000, domRows: 200, initialMs: Math.round(initial), expandedMs: Math.round(expanded), pageMs: Math.round(pageTime), filterMs: Math.round(filterTime), switchAckMs: Math.round(acknowledgement), previewRenderMs: Math.round(previewTime), cachedSwitchMs: Math.round(cachedTime) };
}

export async function testLogPreferenceRestoreRuntime({ testAPI }) {
await waitFor(() => document.querySelector(".desktop-app"), "initial shell missing");
  location.hash = "#core-logs";
  await waitFor(() => document.querySelector(".core-log-status")?.textContent.includes("已加载 8000 条"), "restored per-engine window did not load");
  const logCalls = testAPI.calls.filter((call) => call.path === "/core-logs");
  assert.ok(logCalls.length > 0, "the restored page must still read logs");
  assert.ok(logCalls.every((call) => call.query.includes("agent_id=bravo")), "every log read must use the restored node scope");
  assert.ok(logCalls.some((call) => call.query.includes("limit=2000")), "the restored per-engine window must be requested");
  assert.ok(document.querySelector('[data-core-log-agent="bravo"]').classList.contains("active"), "the restored node must be selected in the sidebar");
  assert.equal(document.querySelector('[data-core-log-agent=""]').classList.contains("active"), false, "the aggregate node link must not stay active");
  assert.equal(document.querySelector('[data-core-log-engine][value="xray"]').getAttribute("aria-pressed"), "true", "the restored engine filter must render as pressed");
  assert.equal(document.querySelector('[data-core-log-level][value="warning"]').getAttribute("aria-pressed"), "true", "the restored level filter must render as pressed");
  assert.equal(document.querySelector('#core-log-filters input[name="q"]').value, "pressure entry 1999", "the restored keyword must fill the search box");
  assert.equal(document.querySelector('#core-log-filters select[name="limit"]').value, "2000", "the restored window must select its option");
  assert.equal(document.querySelector("[data-toggle-core-log-refresh]").getAttribute("aria-checked"), "false", "a paused live stream must stay paused");
  assert.match(document.querySelector("[data-core-log-refresh-label]").textContent, /自动更新已暂停/, "a restored pause must stay visible");
  assert.match(document.querySelector(".core-log-status").textContent, /显示 1 条结果/);
  assert.match(document.querySelector(".core-log-row pre").textContent, /pressure entry 1999/);
  document.querySelector("[data-toggle-core-log-refresh]").click();
  assert.equal(JSON.parse(accountStorage.getItem("qcontrolhub:core-log-preferences")).auto_refresh, true, "resuming the restored stream must be remembered");
}
