import { assert, delay, waitFor } from "./assertions.mjs";

export async function testSystemTCPRuntime({ mode, testAPI }) {
await waitFor(() => document.querySelector(".bbr-card"), "TCP 页面未加载");
  assert.equal(
    [...document.querySelectorAll(".bbr-card")]
      .map((entry) => entry.dataset.refreshKey.replace("bbr-", ""))
      .join(","),
    "alpha,delta,bravo,charlie",
    "TCP 卡片未使用已保存的节点顺序",
  );
  assert.equal(document.querySelector(".bbr-intro"), null, "不应恢复冗余的顶部说明卡");
  if (mode !== "bbr-writeonly")
    assert.notEqual(document.querySelector('.dock-nav a[href="#system-bbr"] svg').innerHTML, document.querySelector('.dock-nav a[href="#traffic"] svg').innerHTML, "TCP 调优和流量侧栏图标重复");
  const card = () => document.querySelector('[data-refresh-key="bbr-alpha"]');
  assert.match(card().textContent, /BBR 已启用/);
  assert.match(card().textContent, /未由 QControlHub 管理/);
  assert.match(card().textContent, /fq_codel/);
  assert.equal(card().querySelector("details"), null, "BBR 二级入口仍使用内联折叠面板");
  const parameters = () => card().querySelector(".bbr-parameters");
  const parametersButton = () => card().querySelector('[data-bbr-dialog-open="bbr-parameters-alpha"]');
  const height = card().offsetHeight;
  parametersButton().focus();
  parametersButton().click();
  assert.ok(parameters().matches(":modal"), "参数详情不是模态弹窗");
  assert.equal(card().offsetHeight, height, "打开详情撑开了卡片");
  assert.match(parameters().textContent, /网卡实际队列/);
  parameters().querySelector("[data-bbr-dialog-close]").click();
  await delay(50);
  assert.equal(document.activeElement, parametersButton(), "关闭弹窗未恢复入口焦点");
  if (mode === "bbr-readonly") {
    assert.equal(document.querySelector("[data-tcp-form]"), null);
    assert.equal(document.querySelector("[data-bbr-action]"), null);
    return;
  }
  assert.ok(document.querySelector('[data-bbr-agent="charlie"]').disabled, "离线节点允许提交");
  assert.ok(document.querySelector('[data-bbr-agent="delta"]').disabled, "旧 Agent 允许提交");
  if (mode === "bbr-writeonly") {
    card().querySelector('[data-bbr-action="enable-bbr"]').click();
    (await waitFor(() => document.querySelector("[data-confirm-dialog][open]"), "无任务读权限时未显示确认框")).querySelector("[data-confirm-accept]").click();
    await waitFor(() => card().textContent.includes("已提交（无任务查看权限）"), "无任务读权限时状态卡在等待执行");
    assert.equal(testAPI.calls.filter((call) => call.path === "/system-tcp/tasks").length, 0, "越权读取任务列表");
    assert.equal(card().querySelector('.bbr-task a[href="#tasks"]'), null, "展示了无权访问的任务链接");
    return;
  }
  const editor = () => card().querySelector(".bbr-editor");
  const openEditor = () => {
    const button = card().querySelector('[data-bbr-dialog-open="bbr-editor-alpha"]');
    button.focus();
    button.click();
  };
  openEditor();
  assert.ok(editor().matches(":modal"), "参数编辑器不是模态弹窗");
  assert.equal(card().offsetHeight, height, "打开编辑器撑开了卡片");
  assert.ok(editor().querySelector('[data-tcp-value="net.core.default_qdisc"] option[value="fq_pie"]'), "缺少 FQ-PIE 自定义选项");
  const field = () => editor().querySelector('[data-tcp-value="net.ipv4.tcp_rmem"]');
  editor().querySelector("form").requestSubmit();
  assert.match(editor().querySelector("[data-tcp-error]").textContent, /请至少勾选/, "空选择没有弹窗内提示");
  field().value = "4096 invalid 33554432";
  field().dispatchEvent(new Event("input", { bubbles: true }));
  editor().querySelector("form").requestSubmit();
  assert.match(editor().querySelector("[data-tcp-error]").textContent, /三个递增整数/, "非法参数没有弹窗内提示");
  assert.equal(document.querySelector("[data-confirm-dialog][open]"), null, "非法参数进入了确认流程");
  assert.equal(testAPI.tcpMutations.length, 0, "非法参数发出了任务");
  field().value = "4096 262144 33554432";
  field().dispatchEvent(new Event("input", { bubbles: true }));
  assert.ok(editor().querySelector("[data-tcp-error]").hidden, "修改参数后仍残留旧错误");
  editor().querySelector("[data-bbr-dialog-close]").click();
  assert.ok(card().querySelector("[data-bbr-draft-label]").textContent.includes("草稿"));
  openEditor();
  assert.equal(field().value, "4096 262144 33554432", "关闭后重开丢失草稿");
  field().focus();
  field().setSelectionRange(5, 11);
  const editorBody = editor().querySelector(".bbr-dialog-body");
  editorBody.scrollTop = 120;
  const refresh = async () => {
    const before = testAPI.calls.filter((call) => call.path === "/system-tcp/tasks").length;
    document.querySelector("[data-bbr-refresh]").click();
    await waitFor(() => testAPI.calls.filter((call) => call.path === "/system-tcp/tasks").length > before, "TCP 刷新未请求");
    await delay(120);
  };
  await refresh();
  assert.equal(field().value, "4096 262144 33554432", "刷新覆盖了 TCP 草稿");
  assert.ok(editor().matches(":modal"), "刷新关闭了 TCP 编辑弹窗");
  assert.equal(document.activeElement, field(), "刷新打断输入焦点");
  assert.equal(field().selectionStart, 5, "刷新打断文字选择");
  assert.equal(editorBody.scrollTop, 120, "刷新重置弹窗滚动位置");
  testAPI.agents[0].metrics.bbr.error = "temporary collection warning";
  await refresh();
  delete testAPI.agents[0].metrics.bbr.error;
  await refresh();
  assert.ok(editor().matches(":modal"), "移除卡片提示导致弹窗丢失遮罩");
  testAPI.agents.reverse();
  await refresh();
  testAPI.agents.reverse();
  await refresh();
  assert.ok(editor().matches(":modal"), "节点重排使弹窗退出模态");
  assert.equal(document.activeElement, field(), "节点重排打断编辑焦点");
  assert.equal(field().selectionStart, 5, "节点重排打断文字选择");
  const backdropGesture = (type, outside) => {
    const rect = editor().getBoundingClientRect();
    editor().dispatchEvent(new MouseEvent(type, { bubbles: true, clientX: rect.left + (outside ? -2 : 2), clientY: rect.top + 2 }));
  };
  backdropGesture("pointerdown", false);
  backdropGesture("click", true);
  assert.ok(editor().matches(":modal"), "从弹窗内拖到遮罩被误判为关闭");
  backdropGesture("pointerdown", true);
  // Native close events are queued. A close used to restore a detached modal
  // can arrive after it has reopened and the next gesture has already begun.
  editor().dispatchEvent(new Event("close"));
  await refresh();
  backdropGesture("click", true);
  assert.equal(editor().open, false, "刷新打断了遮罩关闭手势");
  await delay(50);
  assert.equal(document.activeElement, card().querySelector('[data-bbr-dialog-open="bbr-editor-alpha"]'), "节点重排后关闭弹窗未恢复入口焦点");
  openEditor();
  assert.equal(field().value, "4096 262144 33554432", "遮罩关闭丢失草稿");
  testAPI.agents[0].metrics.bbr.parameters["net.ipv4.tcp_ecn"] = "2";
  await refresh();
  assert.equal(editor().querySelector('[data-tcp-value="net.ipv4.tcp_ecn"]').value, "2", "已打开弹窗未更新实际参数");
  const originalTheme = document.documentElement.dataset.theme;
  document.querySelector("#theme-toggle").click();
  assert.notEqual(document.documentElement.dataset.theme, originalTheme);
  assert.equal(field().value, "4096 262144 33554432");
  editor().querySelector("form").requestSubmit();
  const dialog = await waitFor(() => document.querySelector("[data-confirm-dialog][open]"), "TCP 没有使用共享确认弹窗");
  assert.match(dialog.textContent, /4096 262144 33554432/);
  assert.match(dialog.textContent, /\/etc\/sysctl.d\/90-qcontrolhub-bbr.conf/);
  assert.ok(editor().matches(":modal") && dialog.matches(":modal"), "嵌套确认丢失编辑弹窗");
  const confirmationSnapshot = dialog.textContent;
  testAPI.agents.reverse();
  await refresh();
  testAPI.agents.reverse();
  await refresh();
  assert.ok(dialog.matches(":modal"), "节点重排打断确认弹窗");
  assert.ok(dialog.contains(document.activeElement), "后台刷新抢走确认焦点");
  assert.equal(dialog.textContent, confirmationSnapshot, "后台刷新改写确认快照");
  testAPI.agentsFailure = true;
  dialog.querySelector("[data-confirm-cancel]").click();
  await delay(200);
  assert.equal(testAPI.tcpMutations.length, 0, "取消仍提交任务");
  assert.equal(field().value, "4096 262144 33554432");
  assert.ok(editor().matches(":modal"), "取消确认后没有恢复编辑弹窗");
  assert.ok(!field().disabled, "取消后刷新失败导致编辑器锁死");
  assert.ok(!card().querySelector("[data-bbr-action]").disabled, "取消后刷新失败导致按钮锁死");
  testAPI.tcpFailure = true;
  editor().querySelector("form").requestSubmit();
  (await waitFor(() => document.querySelector("[data-confirm-dialog][open]"), "失败测试没有确认弹窗")).querySelector("[data-confirm-accept]").click();
  await waitFor(() => testAPI.tcpMutations.length === 1, "TCP 任务未发出");
  await delay(200);
  assert.equal(field().value, "4096 262144 33554432", "失败丢失草稿");
  assert.ok(editor().matches(":modal"), "失败关闭了编辑弹窗");
  assert.match(editor().querySelector("[data-tcp-error]").textContent, /服务暂不可用，请稍后重试/, "中文错误提示在弹窗外不可见");
  assert.ok(!field().disabled, "提交失败且刷新失败导致编辑器锁死");
  testAPI.agentsFailure = false;
  testAPI.tcpFailure = false;
  editor().querySelector("form").requestSubmit();
  (await waitFor(() => document.querySelector("[data-confirm-dialog][open]"), "重试没有确认弹窗")).querySelector("[data-confirm-accept]").click();
  await waitFor(() => testAPI.tcpTasks.length === 1, "TCP 任务未创建");
  await delay(200);
  const payload = testAPI.tcpMutations.at(-1);
  assert.equal(payload.action, "configure-tcp");
  assert.equal(payload.engine, "");
  assert.equal(Object.keys(payload.tcp_settings).length, 1, "提交了未勾选的参数");
  assert.equal(payload.tcp_settings["net.ipv4.tcp_rmem"], "4096 262144 33554432");
  assert.ok(card().querySelector("[data-bbr-action]").disabled, "进行中任务未禁止重复提交");
  assert.match(card().textContent, /等待执行/);
  assert.equal(editor().open, false, "成功提交后没有返回节点卡片");
  testAPI.tcpTasks[0].status = "succeeded";
  testAPI.agents[0].metrics.bbr.parameters["net.ipv4.tcp_rmem"] = "4096 262144 33554432";
  testAPI.agents[0].metrics.bbr.persistence = "managed";
  testAPI.agents[0].metrics.bbr.configured_parameters = { "net.ipv4.tcp_rmem": "4096 262144 33554432" };
  await refresh();
  assert.match(card().textContent, /执行成功/);
  assert.ok(!card().querySelector("[data-bbr-action]").disabled);
  openEditor();
  field().value = "4096 524288 67108864";
  field().dispatchEvent(new Event("input", { bubbles: true }));
  editor().querySelector("[data-tcp-reset]").click();
  await waitFor(() => document.querySelector("[data-confirm-dialog][open]"), "取消清空测试未显示确认框");
  testAPI.agents.reverse();
  await refresh();
  testAPI.agents.reverse();
  await refresh();
  document.querySelector("[data-confirm-cancel]").click();
  await delay(50);
  assert.ok(editor().matches(":modal"), "取消清空后编辑弹窗丢失遮罩");
  assert.equal(field().value, "4096 524288 67108864", "取消清空丢失草稿");
  testAPI.agentsFailure = true;
  editor().querySelector("[data-tcp-reset]").click();
  (await waitFor(() => document.querySelector("[data-confirm-dialog][open]"), "清空草稿未确认")).querySelector("[data-confirm-accept]").click();
  await delay(200);
  assert.equal(editor().querySelector('[data-tcp-selected="net.ipv4.tcp_rmem"]').checked, false, "清空后仍勾选参数");
  assert.equal(field().value, "4096 262144 33554432", "清空后未恢复当前值");
  assert.ok(!field().disabled, "清空草稿依赖网络成功才能解锁");
  await refresh();
  assert.match(document.querySelector("[data-bbr-refresh-status]").textContent, /刷新失败/);
  assert.ok(card(), "刷新失败清空了状态");
  testAPI.agentsFailure = false;
  testAPI.tcpTasks[0].status = "pending";
  await refresh();
  assert.ok(card().querySelector("[data-bbr-action]").disabled);
  assert.ok(field().disabled, "打开的编辑器未随任务状态禁用");
  assert.match(editor().querySelector("[data-bbr-dialog-status]").textContent, /等待执行/);
  testAPI.tcpTasks = [];
  await refresh();
  assert.ok(!card().querySelector("[data-bbr-action]").disabled, "已被服务端移除的任务仍永久阻塞操作");
  assert.equal(card().querySelector(".bbr-task"), null, "仍显示被清理的任务历史");
  assert.ok(!field().disabled, "打开的编辑器未随任务清理解锁");
  editor().querySelector("[data-bbr-dialog-close]").click();
  card().querySelector('[data-bbr-action="enable-bbr"]').click();
  await waitFor(() => document.querySelector("[data-confirm-dialog][open]"), "节点状态变化测试未显示弹窗");
  const beforeOffline = testAPI.tcpMutations.length;
  testAPI.agents[0].status = "offline";
  await refresh();
  document.querySelector("[data-confirm-dialog][open] [data-confirm-accept]").click();
  await delay(200);
  assert.equal(testAPI.tcpMutations.length, beforeOffline, "确认框打开期间节点离线仍然提交");
  testAPI.agents[0].status = "online";
  await refresh();
  parametersButton().click();
  testAPI.agents[0].metrics.bbr.qdiscs = [{ device: "eth0", kind: "fq_pie", root: true }];
  await refresh();
  assert.ok(parameters().matches(":modal"));
  assert.match(parameters().querySelectorAll("table")[1].textContent, /fq_pie/, "详情弹窗未更新网卡实际队列");
  location.hash = "#system-bbr-agent-bravo";
  await waitFor(() => document.querySelectorAll(".bbr-card").length === 1 && document.querySelector('[data-refresh-key="bbr-bravo"]'), "节点筛选失败");
  assert.equal(document.querySelector(".bbr-dialog[open]"), null, "切换节点后仍有旧弹窗覆盖页面");
  document.querySelector('[data-bbr-dialog-open="bbr-editor-bravo"]').click();
  assert.ok(document.querySelector(".bbr-editor").matches(":modal"));
  location.hash = "#node-settings";
  await waitFor(() => document.querySelector(".node-card"), "离开 TCP 页面失败");
  const calls = testAPI.calls.filter((call) => call.path === "/system-tcp/tasks").length;
  await delay(5200);
  assert.equal(testAPI.calls.filter((call) => call.path === "/system-tcp/tasks").length, calls, "离开 TCP 页面后继续轮询");
  assert.equal(testAPI.calls.filter((call) => call.path === "/system-tcp/parameters").length, 1, "每次轮询都重复读取不变的参数规则");
}
