import { assert, waitFor } from "./assertions.mjs";
import { accountStorage } from "../modules/account-storage.js";

export async function testTrafficLayoutRuntime({ testAPI }) {
    await waitFor(()=>document.querySelectorAll(".traffic-accounting-panel").length===4,"traffic accounting cards did not load");
    const cardNodes = () => [...document.querySelectorAll(".traffic-policy-grid > [data-traffic-agent-card]")].map(card => card.dataset.trafficAgentCard).join(",");
    const sidebarNodes = () => [...document.querySelectorAll(".context-list [data-context-traffic-agent]")].map(link => link.dataset.contextTrafficAgent).join(",");
    assert.equal(cardNodes(), "alpha,delta,bravo,charlie", "default traffic cards must follow saved node order");
    assert.equal(cardNodes(), sidebarNodes(), "default traffic cards and the node sidebar must agree");
    assert.equal(accountStorage.getItem("qcontrolhub:traffic-card-order"), null, "default rendering must not freeze a custom card order");
    assert.equal(document.querySelectorAll(".traffic-accounting-panel.bad").length,1,"scope limitation must not be rendered as an error");
    assert.equal(document.querySelectorAll(".traffic-accounting-details[open]").length,0,"diagnostics should be collapsed initially");
    assert.equal(document.querySelectorAll(".traffic-status-dialog[open]").length,0,"status dialogs must start closed");
    document.querySelector("[data-traffic-status-open]").click();
    assert.ok(document.querySelector(".traffic-status-dialog").open,"status button should open dialog");
    const details = document.querySelector(".traffic-accounting-details"); details.querySelector("summary").click();
    assert.ok(details.open && details.textContent.includes("single-protocol"),"original diagnostic inaccessible");
    if (!new URLSearchParams(location.search).has("preview")) {
      const dialog = document.querySelector(".traffic-status-dialog");
      const policy = testAPI.trafficPolicies[0];
      policy.enforcement_error = "API connection refused";
      await waitFor(()=>dialog.textContent.includes("API connection refused"),"open status dialog did not refresh failure");
      assert.ok(dialog.open && dialog.querySelector("details").open,"refresh closed dialog or details");
      policy.enforcement_error = "";
      policy.accounting = {source:"core-api",client_received:1024,client_sent:2048,target_received:4096,target_sent:8192};
      await waitFor(()=>dialog.textContent.includes("双链路统计") && !dialog.textContent.includes("API connection refused"),"open dialog did not recover");
      const previousLegs = dialog.querySelector(".traffic-accounting-legs").textContent;
      policy.accounting.target_sent = 16384;
      await waitFor(()=>dialog.querySelector(".traffic-accounting-legs").textContent !== previousLegs,"open dialog counters did not refresh");
      assert.ok(dialog.open && dialog.querySelector("details").open,"counter refresh closed dialog or details");
    }
    details.querySelector("summary").click();
    document.querySelector("[data-traffic-status-close]").click();
    assert.ok(!document.querySelector(".traffic-status-dialog").open,"status dialog should close");
    const quota = document.querySelector('[data-traffic-edit-form] [name="limit_gb"]');
    assert.ok(quota && !quota.required && quota.value === "" && quota.checkValidity(), "monitor-only quota must allow an empty value");
    quota.value = "0";
    assert.ok(quota.checkValidity(), "zero must be a valid monitor-only quota");
    quota.value = "";
    if (new URLSearchParams(location.search).has("preview")) await new Promise(() => {});
    accountStorage.setItem("qcontrolhub:node-card-order", JSON.stringify(["bravo", "alpha", "delta", "charlie"]));
    await waitFor(() => cardNodes() === "bravo,alpha,delta,charlie", "polling did not apply the updated node order");
    assert.equal(cardNodes(), sidebarNodes(), "polling must keep cards and the sidebar in the same node order");
    accountStorage.setItem("qcontrolhub:traffic-card-order", JSON.stringify(["charlie:8445", "alpha:8443"]));
    await waitFor(() => cardNodes() === "charlie,alpha,bravo,delta", "custom traffic order must take priority over node order");
    document.querySelector('[href="#traffic-agent-bravo"]').click();
    await waitFor(() => cardNodes() === "bravo", "node filtering did not keep the selected node's card");
    document.querySelector('[href="#traffic-all"]').click();
    await waitFor(() => cardNodes() === "charlie,alpha,bravo,delta", "clearing a filter did not restore custom card order");
    const posts = () => testAPI.calls.filter(call => call.path === "/traffic-endpoints/sync" && call.method === "POST").length;
    const openSync = async () => {
      document.querySelector("[data-traffic-sync]").click();
      return waitFor(() => document.querySelector("[data-traffic-sync-dialog][open]"), "sync selection dialog did not open");
    };
    let dialog = await openSync();
    await waitFor(() => dialog.querySelectorAll("[data-sync-choice]").length === 3, "candidates did not load");
    assert.equal(posts(), 0, "preview must not write");
    assert.ok(dialog.querySelector("[data-sync-submit]").disabled, "nothing selected by default");
    assert.ok(dialog.textContent.includes("已删除 · 可恢复") && dialog.textContent.includes("未监控 · 可添加"), "candidate types missing");
    dialog.querySelector("[data-sync-close]").click();
    assert.equal(posts(), 0, "cancel must not write");
    assert.ok(!document.querySelector("[data-traffic-sync]").disabled, "cancel must unlock sync");
    testAPI.trafficPreviewFailure = true;
    dialog = await openSync();
    await waitFor(() => !dialog.querySelector("[data-sync-retry]").hidden, "preview failure must allow retry");
    assert.ok(dialog.querySelector("[data-sync-error]").textContent.includes("服务器处理失败"), "Chinese preview error hidden");
    testAPI.trafficPreviewFailure = false;
    dialog.querySelector("[data-sync-retry]").click();
    await waitFor(() => dialog.querySelectorAll("[data-sync-choice]").length === 3, "retry did not load");
    dialog.querySelector("[data-sync-all]").click();
    assert.equal(dialog.querySelectorAll("[data-sync-choice]:checked").length, 3, "select all failed");
    dialog.querySelector('[data-sync-choice="2"]').click();
    assert.ok(dialog.querySelector("[data-sync-all]").indeterminate, "partial selection indicator missing");
    const reads = testAPI.calls.filter(call => call.path === "/traffic-policies").length;
    await waitFor(() => testAPI.calls.filter(call => call.path === "/traffic-policies").length > reads, "background poll stopped");
    assert.ok(dialog.open && dialog.querySelectorAll("[data-sync-choice]:checked").length === 2, "polling reset selection");
    assert.ok(document.querySelector("[data-traffic-sync]").disabled, "polling unlocked duplicate dialog");
    testAPI.trafficSyncFailure = true;
    dialog.querySelector("[data-sync-submit]").click();
    await waitFor(() => posts() === 1 && !dialog.querySelector("[data-sync-submit]").disabled
      && !dialog.querySelector("[data-sync-error]").hidden
      && dialog.querySelector("[data-sync-error]").textContent.includes("服务器处理失败"), "Chinese mutation error hidden");
    assert.equal(dialog.querySelectorAll("[data-sync-choice]:checked").length, 2, "failure lost selection");
    testAPI.trafficSyncFailure = false;
    let finish;
    testAPI.trafficSyncGate = new Promise(resolve => { finish = resolve; });
    dialog.querySelector("[data-sync-submit]").click();
    dialog.querySelector("[data-sync-submit]").click();
    assert.equal(posts(), 2, "duplicate submission not blocked");
    assert.ok(dialog.querySelector("[data-sync-close]").disabled, "pending mutation close must be disabled");
    assert.equal(JSON.stringify(testAPI.trafficSelection), JSON.stringify([{agent_id:"alpha",port:443},{agent_id:"bravo",port:9443}]), "must send only selected identities");
    finish();
    await waitFor(() => !document.querySelector("[data-traffic-sync-dialog]") && !document.querySelector("[data-traffic-sync]").disabled, "success did not close and unlock");
    assert.equal(testAPI.trafficCandidates.length, 1, "unselected candidate changed");
    testAPI.trafficSyncGate = null;
    dialog = await openSync();
    await waitFor(() => dialog.querySelectorAll("[data-sync-choice]").length === 1, "reopen did not reload remaining candidates");
    dialog.querySelector("[data-sync-close]").click();
    testAPI.trafficCandidates = [];
    dialog = await openSync();
    await waitFor(() => dialog.textContent.includes("暂无需要同步的端口"), "empty state missing");
    assert.ok(dialog.querySelector("[data-sync-submit]").disabled, "empty list allows write");
    dialog.querySelector("[data-sync-close]").click();
    let finishPreview;
    testAPI.trafficPreviewGate = new Promise(resolve => { finishPreview = resolve; });
    await openSync();
    location.hash = "#node-settings";
    await waitFor(() => !document.querySelector("[data-traffic-sync-dialog]"), "navigation left a modal behind");
    finishPreview();
    assert.equal(posts(), 2, "navigation must not write");
    testAPI.trafficPreviewGate = null;
    location.hash = "#traffic";
    await waitFor(() => !document.querySelector(".workspace-main[aria-busy]") && document.querySelector("[data-traffic-sync]"), "traffic return failed");
    testAPI.trafficCandidates = [{agent_id:"alpha",name:"late selection",engine:"xray",port:11443,protocol:"both",kind:"new"}];
    dialog = await openSync();
    await waitFor(() => dialog.querySelector("[data-sync-choice]"), "late selection missing");
    dialog.querySelector("[data-sync-choice]").click();
    testAPI.trafficSyncGate = new Promise(resolve => { finish = resolve; });
    dialog.querySelector("[data-sync-submit]").click();
    assert.equal(posts(), 3, "selected navigation test did not submit");
    location.hash = "#node-settings";
    await waitFor(() => !document.querySelector("[data-traffic-sync-dialog]"), "pending write dialog survived navigation");
    finish();
    await waitFor(() => testAPI.trafficCandidates.length === 0, "late mutation did not finish");
    assert.ok(!document.querySelector("[data-traffic-sync]"), "late mutation returned to traffic route");
    testAPI.trafficSyncGate = null;
    location.hash = "#traffic";
    await waitFor(() => document.querySelector("[data-traffic-sync]"), "traffic return before expiry failed");
    testAPI.trafficPreviewUnauthorized = true;
    document.querySelector("[data-traffic-sync]").click();
    await waitFor(() => document.querySelector("#login-form"), "expired session did not reach login");
    assert.ok(!document.querySelector("[data-traffic-sync-dialog]"), "expired session left an orphan modal blocking login");
}
