const app = document.querySelector('#app');
const engines = ['mihomo', 'xray', 'sing-box', 'ss-rust'];
const actions = ['validate', 'deploy', 'start', 'stop', 'restart', 'status', 'install', 'read-config'];
const state = { session: null, route: location.hash.slice(1) || 'dashboard', data: {}, busy: false };

const esc = value => String(value ?? '').replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const date = value => value ? new Date(value).toLocaleString() : '-';
const bytes = value => { const n = Number(value || 0); if (!n) return '0 B'; const units = ['B','KB','MB','GB','TB']; const i = Math.min(Math.floor(Math.log(n) / Math.log(1024)), units.length - 1); return `${(n / (1024 ** i)).toFixed(i ? 1 : 0)} ${units[i]}`; };
const label = value => String(value || '').replaceAll('_', ' ');
const can = role => ({readonly: 1, operator: 2, admin: 3}[state.session?.role] || 0) >= ({readonly: 1, operator: 2, admin: 3}[role] || 0);

async function api(path, options = {}) {
  const headers = {'Accept': 'application/json', ...(options.body ? {'Content-Type': 'application/json'} : {}), ...(options.headers || {})};
  if (state.session?.csrf && options.method && !['GET','HEAD','OPTIONS'].includes(options.method)) headers['X-QControlHub-CSRF'] = state.session.csrf;
  const response = await fetch(`/api/v1${path}`, {...options, headers, credentials: 'same-origin'});
  if (response.status === 401) { state.session = null; renderLogin(); throw new Error('登录已失效'); }
  if (!response.ok) { let body = {}; try { body = await response.json(); } catch {} throw new Error(body.error || `请求失败 (${response.status})`); }
  if (response.status === 204) return null;
  return response.json();
}

async function ensureSession() {
  try { state.session = await api('/auth/session'); return true; } catch { state.session = null; return false; }
}

function renderLogin(message = '') {
  app.innerHTML = `<main class="login-wrap"><section class="login-panel"><div class="brand-mark">QC</div><h1>QControlHub</h1><p class="muted">Linux 节点控制平面</p>${message ? `<div class="alert error">${esc(message)}</div>` : ''}<form id="login-form"><label>管理令牌<input name="token" type="password" autocomplete="current-password" required minlength="32" placeholder="输入 QCH_ADMIN_TOKEN"></label><button class="primary" type="submit">登录控制台</button></form></section></main>`;
  document.querySelector('#login-form').addEventListener('submit', async event => { event.preventDefault(); const token = new FormData(event.currentTarget).get('token'); const button = event.currentTarget.querySelector('button'); button.disabled = true; try { state.session = await api('/auth/login', {method: 'POST', body: JSON.stringify({token})}); location.hash = '#dashboard'; await render(); } catch (error) { renderLogin(error.message); } });
}

function shell(content, title) {
  const links = [['dashboard','总览','⌂'],['agents','节点','◈'],['configs','配置','▤'],['tasks','任务','✓'],['settings','设置','⚙'],['audit','审计','≡']];
  app.innerHTML = `<div class="layout"><aside class="sidebar"><div class="logo"><span>QC</span><strong>QControlHub</strong></div><nav>${links.map(([id, text, icon]) => `<a class="${state.route === id ? 'active' : ''}" href="#${id}"><i>${icon}</i>${text}</a>`).join('')}</nav><div class="side-foot"><span class="role">${esc(state.session.role)}</span><button id="logout" class="quiet">退出</button></div></aside><main class="main"><header><div><p class="eyebrow">控制平面</p><h1>${esc(title)}</h1></div><div class="header-actions"><span class="status-dot">已连接</span><button id="refresh" class="icon-button" title="刷新">↻</button></div></header><div id="content">${content}</div></main></div>`;
  document.querySelector('#logout').onclick = async () => { try { await api('/auth/logout', {method: 'POST'}); } catch {} state.session = null; renderLogin(); };
  document.querySelector('#refresh').onclick = () => render();
}

function card(title, value, note, tone = '') { return `<section class="stat ${tone}"><span>${esc(title)}</span><strong>${esc(value)}</strong><small>${esc(note)}</small></section>`; }

async function dashboard() {
  const overview = await api('/overview'); state.data.overview = overview;
  shell(`<div class="stats">${card('节点总数', overview.agents, `${overview.agents_online} 个在线`, 'blue')}${card('配置档案', overview.configs, `${overview.node_configs} 个节点配置`)}${card('待处理任务', overview.tasks_pending, `${overview.tasks_queued} 个排队中`, 'amber')}${card('失败任务', overview.tasks_failed, '需要关注', overview.tasks_failed ? 'red' : '')}</div><section class="section"><div class="section-head"><div><h2>运行概况</h2><p class="muted">控制面实时汇总</p></div><a class="button" href="#agents">查看节点</a></div><div class="empty"><span class="empty-icon">◌</span><strong>所有操作通过 API 完成</strong><p>节点心跳、配置版本和任务状态会在后台持续更新。</p></div></section>`, '总览');
}

async function agents() {
  const [agents, tokens] = await Promise.all([api('/agents'), api('/enrollment-tokens')]); state.data.agents = agents;
  const rows = agents.length ? agents.map(agent => `<tr><td><strong>${esc(agent.name)}</strong><small class="sub">${esc(agent.id)}</small></td><td><span class="pill ${agent.status === 'online' ? 'ok' : ''}">${esc(agent.status || 'offline')}</span></td><td>${esc(agent.os)} / ${esc(agent.arch)}<small class="sub">${esc(agent.version || '-')}</small></td><td>${(agent.capabilities || []).map(esc).join(', ') || '-'}</td><td>${agent.metrics?.memory_total_bytes ? `${bytes(agent.metrics.memory_used_bytes)} / ${bytes(agent.metrics.memory_total_bytes)}` : '-'}<small class="sub">CPU ${Number(agent.metrics?.cpu_percent || 0).toFixed(1)}%</small></td><td>${date(agent.last_seen)}</td><td class="actions"><button class="button small" data-config="${esc(agent.id)}">配置</button>${can('admin') ? `<button class="danger-link" data-delete="${esc(agent.id)}">移除</button>` : ''}</td></tr>`).join('') : `<tr><td colspan="7" class="table-empty">暂无节点</td></tr>`;
  const tokenRows = tokens.length ? tokens.map(token => `<tr><td>${esc(token.name)}</td><td>${date(token.expires_at)}</td><td>${token.used_count}/${token.max_uses}</td><td>${token.revoked_at ? '已吊销' : '有效'}</td><td>${can('admin') && !token.revoked_at ? `<button class="danger-link" data-revoke="${esc(token.id)}">吊销</button>` : ''}</td></tr>`).join('') : `<tr><td colspan="5" class="table-empty">暂无注册码</td></tr>`;
  shell(`<section class="section"><div class="section-head"><div><h2>节点</h2><p class="muted">已注册的 Linux Agent</p></div>${can('admin') ? '<button id="new-token" class="button primary">生成注册码</button>' : ''}</div><div class="table-wrap"><table><thead><tr><th>名称</th><th>状态</th><th>系统</th><th>能力</th><th>资源</th><th>最后心跳</th><th>操作</th></tr></thead><tbody>${rows}</tbody></table></div></section><section class="section"><div class="section-head"><div><h2>入网注册码</h2><p class="muted">一次性或限次使用</p></div></div><div class="table-wrap"><table><thead><tr><th>名称</th><th>过期时间</th><th>使用次数</th><th>状态</th><th></th></tr></thead><tbody>${tokenRows}</tbody></table></div></section>`, '节点');
  document.querySelector('#new-token')?.addEventListener('click', async () => { const name = prompt('注册码名称', '新节点'); if (!name) return; try { const created = await api('/enrollment-tokens', {method:'POST', body: JSON.stringify({name, ttl_minutes: 15, max_uses: 1})}); alert(`请立即复制注册码：\n\n${created.token}`); render(); } catch (error) { alert(error.message); } });
  document.querySelectorAll('[data-revoke]').forEach(button => button.onclick = async () => { if (!confirm('确认吊销该注册码？')) return; try { await api(`/enrollment-tokens/${button.dataset.revoke}`, {method:'DELETE'}); render(); } catch (error) { alert(error.message); } });
  document.querySelectorAll('[data-delete]').forEach(button => button.onclick = async () => { if (!confirm('确认移除该节点？现有连接会被断开。')) return; try { await api(`/agents/${button.dataset.delete}`, {method:'DELETE'}); render(); } catch (error) { alert(error.message); } });
  document.querySelectorAll('[data-config]').forEach(button => button.onclick = () => { state.data.agentId = button.dataset.config; location.hash = '#agent-config'; });
}

async function agentConfig() {
  const agent = (state.data.agents || await api('/agents')).find(item => item.id === state.data.agentId); if (!agent) { location.hash = '#agents'; return; }
  const engine = state.data.engine || agent.capabilities?.[0] || engines[0]; let current = {}; try { current = await api(`/agents/${encodeURIComponent(agent.id)}/configs/${encodeURIComponent(engine)}`); } catch (error) { if (!error.message.includes('404')) throw error; }
  shell(`<section class="section narrow"><div class="section-head"><div><h2>${esc(agent.name)} / 节点配置</h2><p class="muted">${esc(agent.id)}</p></div><a class="button" href="#agents">返回节点</a></div><div class="toolbar"><label>内核<select id="engine">${(agent.capabilities || engines).map(item => `<option value="${esc(item)}" ${item === engine ? 'selected' : ''}>${esc(item)}</option>`).join('')}</select></label></div><form id="agent-config-form"><div class="form-grid"><label>名称<input name="name" value="${esc(current.name || agent.name + ' 配置')}"></label><label>版本<input name="version" type="number" min="0" value="${Number(current.version || 0)}" readonly></label></div><label>配置正文<textarea name="content" rows="22" required>${esc(current.content || '')}</textarea><small class="muted">保存前由控制面校验配置格式。</small><div class="form-actions"><button class="button primary" type="submit">保存节点配置</button></div></form></section>`, '节点配置');
  document.querySelector('#engine').onchange = event => { state.data.engine = event.target.value; agentConfig(); };
  document.querySelector('#agent-config-form').onsubmit = async event => { event.preventDefault(); const form = new FormData(event.currentTarget); try { await api(`/agents/${encodeURIComponent(agent.id)}/configs/${encodeURIComponent(engine)}`, {method:'PUT', body: JSON.stringify({name: form.get('name'), engine, content: form.get('content'), version: Number(form.get('version') || 0)})}); alert('节点配置已保存'); agentConfig(); } catch (error) { alert(error.message); } };
}

async function configs() {
  const [items, templates] = await Promise.all([api('/configs'), api('/templates')]);
  const rows = items.length ? items.map(item => `<tr><td><strong>${esc(item.name)}</strong><small class="sub">${esc(item.id)}</small></td><td>${esc(item.engine)}</td><td>v${item.version}</td><td>${esc(item.description || '-')}</td><td>${date(item.updated_at)}</td><td class="actions">${can('operator') ? `<button class="button small" data-edit="${esc(item.id)}">编辑</button>` : ''}${can('admin') ? `<button class="danger-link" data-remove="${esc(item.id)}">删除</button>` : ''}</td></tr>`).join('') : `<tr><td colspan="6" class="table-empty">暂无配置档案</td></tr>`;
  const templateRows = templates.length ? templates.map(item => `<tr><td>${esc(item.name)}</td><td>${esc(item.engine)}</td><td>${date(item.updated_at)}</td><td class="actions">${can('operator') ? `<button class="button small" data-apply-template="${esc(item.id)}">应用到节点</button>` : ''}${can('admin') ? `<button class="danger-link" data-delete-template="${esc(item.id)}">删除</button>` : ''}</td></tr>`).join('') : `<tr><td colspan="4" class="table-empty">暂无模板</td></tr>`;
  shell(`<section class="section"><div class="section-head"><div><h2>配置档案</h2><p class="muted">可复用的全局配置版本</p></div>${can('operator') ? '<button id="new-config" class="button primary">新建配置</button>' : ''}</div><div class="table-wrap"><table><thead><tr><th>名称</th><th>内核</th><th>版本</th><th>说明</th><th>更新时间</th><th>操作</th></tr></thead><tbody>${rows}</tbody></table></div></section><section class="section"><div class="section-head"><div><h2>配置模板</h2><p class="muted">支持 {{node_name}}、{{lan_ip}}、{{random_port}}</p></div>${can('operator') ? '<button id="new-template" class="button">新建模板</button>' : ''}</div><div class="table-wrap"><table><thead><tr><th>名称</th><th>内核</th><th>更新时间</th><th>操作</th></tr></thead><tbody>${templateRows}</tbody></table></div></section>`, '配置');
  document.querySelector('#new-config')?.addEventListener('click', () => configDialog());
  document.querySelectorAll('[data-edit]').forEach(button => button.onclick = () => configDialog(items.find(item => item.id === button.dataset.edit)));
  document.querySelectorAll('[data-remove]').forEach(button => button.onclick = async () => { if (!confirm('确认删除配置？')) return; try { await api(`/configs/${button.dataset.remove}`, {method:'DELETE'}); render(); } catch (error) { alert(error.message); } });
  document.querySelector('#new-template')?.addEventListener('click', () => templateDialog());
  document.querySelectorAll('[data-delete-template]').forEach(button => button.onclick = async () => { if (!confirm('确认删除模板？')) return; try { await api(`/templates/${button.dataset.deleteTemplate}`, {method:'DELETE'}); render(); } catch (error) { alert(error.message); } });
  document.querySelectorAll('[data-apply-template]').forEach(button => button.onclick = async () => { const agent = prompt('输入目标节点 ID'); if (!agent) return; try { await api(`/templates/${button.dataset.applyTemplate}/apply`, {method:'POST', body: JSON.stringify({agent_id: agent})}); alert('模板已应用'); } catch (error) { alert(error.message); } });
}

function dialog(title, body, submit) { const wrap = document.createElement('div'); wrap.className = 'modal-backdrop'; wrap.innerHTML = `<section class="modal"><div class="section-head"><h2>${esc(title)}</h2><button class="icon-button" data-close>×</button></div><form>${body}<div class="form-actions"><button class="button" type="button" data-close>取消</button><button class="button primary" type="submit">保存</button></div></form></section>`; document.body.append(wrap); wrap.querySelectorAll('[data-close]').forEach(item => item.onclick = () => wrap.remove()); wrap.querySelector('form').onsubmit = async event => { event.preventDefault(); try { await submit(new FormData(event.currentTarget)); wrap.remove(); render(); } catch (error) { alert(error.message); } }; }
function configDialog(item = {}) { dialog(item.id ? '编辑配置' : '新建配置', `<label>名称<input name="name" value="${esc(item.name)}" required></label><label>说明<input name="description" value="${esc(item.description)}"></label><label>内核<select name="engine">${engines.map(engine => `<option ${engine === item.engine ? 'selected' : ''}>${engine}</option>`).join('')}</select></label><label>配置正文<textarea name="content" rows="16" required>${esc(item.content)}</textarea>`, async form => { const payload = {name: form.get('name'), description: form.get('description'), engine: form.get('engine'), content: form.get('content'), version: Number(item.version || 0)}; await api(item.id ? `/configs/${item.id}` : '/configs', {method: item.id ? 'PUT' : 'POST', body: JSON.stringify(payload)}); }); }
function templateDialog() { dialog('新建模板', `<label>名称<input name="name" required></label><label>内核<select name="engine">${engines.map(engine => `<option>${engine}</option>`).join('')}</select></label><label>模板正文<textarea name="content" rows="16" required></textarea></label>`, async form => api('/templates', {method:'POST', body: JSON.stringify({name: form.get('name'), engine: form.get('engine'), content: form.get('content')})})); }

async function tasks() {
  const [items, agents] = await Promise.all([api('/tasks?limit=100'), api('/agents')]);
  const rows = items.length ? items.map(item => `<tr><td><strong>${esc(item.id)}</strong><small class="sub">${date(item.created_at)}</small></td><td>${esc(agents.find(agent => agent.id === item.agent_id)?.name || item.agent_id)}</td><td>${esc(item.engine)} / ${esc(item.action)}</td><td><span class="pill status-${esc(item.status)}">${esc(item.status)}</span></td><td>${esc(item.error || item.output || '-')}</td><td class="actions">${item.status === 'pending' && can('operator') ? `<button class="danger-link" data-cancel="${esc(item.id)}">取消</button>` : ''}${['failed','canceled'].includes(item.status) && can('operator') ? `<button class="button small" data-retry="${esc(item.id)}">重试</button>` : ''}</td></tr>`).join('') : `<tr><td colspan="6" class="table-empty">暂无任务</td></tr>`;
  shell(`<section class="section"><div class="section-head"><div><h2>任务</h2><p class="muted">远程校验、部署和服务操作</p></div>${can('operator') ? '<button id="new-task" class="button primary">创建任务</button>' : ''}</div><div class="table-wrap"><table><thead><tr><th>任务</th><th>节点</th><th>动作</th><th>状态</th><th>结果</th><th>操作</th></tr></thead><tbody>${rows}</tbody></table></div></section>`, '任务');
  document.querySelector('#new-task')?.addEventListener('click', () => taskDialog(agents));
  document.querySelectorAll('[data-cancel]').forEach(button => button.onclick = async () => { try { await api(`/tasks/${button.dataset.cancel}`, {method:'DELETE'}); render(); } catch (error) { alert(error.message); } });
  document.querySelectorAll('[data-retry]').forEach(button => button.onclick = async () => { try { await api(`/tasks/${button.dataset.retry}/retry`, {method:'POST'}); render(); } catch (error) { alert(error.message); } });
}
function taskDialog(agents) { dialog('创建任务', `<label>节点<select name="agent_id" required>${agents.map(agent => `<option value="${esc(agent.id)}">${esc(agent.name)} (${esc(agent.id)})</option>`).join('')}</select></label><label>内核<select name="engine">${engines.map(engine => `<option>${engine}</option>`).join('')}</select></label><label>动作<select name="action">${actions.map(action => `<option>${action}</option>`).join('')}</select></label><label>版本（仅 install）<input name="core_version" placeholder="stable"></label>`, async form => api('/tasks', {method:'POST', body: JSON.stringify({agent_id: form.get('agent_id'), engine: form.get('engine'), action: form.get('action'), core_version: form.get('core_version')})})); }

async function settings() { const item = await api('/settings'); shell(`<section class="section narrow"><div class="section-head"><div><h2>系统设置</h2><p class="muted">控制台显示和任务行为</p></div></div><form id="settings-form"><div class="form-grid"><label>面板名称<input name="panel_name" value="${esc(item.panel_name)}" required></label><label>注册码有效期<select name="enrollment_ttl_minutes">${[10,15,30,60].map(value => `<option value="${value}" ${value === item.enrollment_ttl_minutes ? 'selected' : ''}>${value} 分钟</option>`).join('')}</select></label><label>任务分页<select name="task_page_size">${[50,100,500].map(value => `<option value="${value}" ${value === item.task_page_size ? 'selected' : ''}>${value} 条</option>`).join('')}</select></label><label>轮询间隔<select name="task_poll_interval_ms">${[600,1000,2000,5000].map(value => `<option value="${value}" ${value === item.task_poll_interval_ms ? 'selected' : ''}>${value} ms</option>`).join('')}</select></label></div><label>说明<input name="panel_description" value="${esc(item.panel_description)}"></label><label>Webhook URL<input name="webhook_url" type="url" value="${esc(item.webhook_url)}" placeholder="可选"></label><div class="form-actions"><button class="button primary">保存设置</button></div></form></section>`, '设置'); document.querySelector('#settings-form').onsubmit = async event => { event.preventDefault(); const form = new FormData(event.currentTarget); try { await api('/settings', {method:'PUT', body: JSON.stringify({panel_name:form.get('panel_name'), panel_description:form.get('panel_description'), enrollment_ttl_minutes:Number(form.get('enrollment_ttl_minutes')), task_page_size:Number(form.get('task_page_size')), task_poll_interval_ms:Number(form.get('task_poll_interval_ms')), webhook_url:form.get('webhook_url')})}); alert('设置已保存'); } catch (error) { alert(error.message); } }; }

async function audit() { const items = await api('/audit?limit=100'); const rows = items.length ? items.map(item => `<tr><td>${date(item.acted_at)}</td><td>${esc(item.actor)}</td><td>${esc(item.action)}</td><td>${esc(item.target || '-')}</td><td>${esc(item.detail || '-')}</td><td>${esc(item.remote_ip || '-')}</td></tr>`).join('') : `<tr><td colspan="6" class="table-empty">暂无审计记录</td></tr>`; shell(`<section class="section"><div class="section-head"><div><h2>审计记录</h2><p class="muted">最近 100 条管理操作</p></div></div><div class="table-wrap"><table><thead><tr><th>时间</th><th>角色</th><th>动作</th><th>目标</th><th>详情</th><th>来源</th></tr></thead><tbody>${rows}</tbody></table></div></section>`, '审计'); }

async function render() { if (state.busy) return; state.busy = true; state.route = location.hash.slice(1) || 'dashboard'; try { if (!state.session && !(await ensureSession())) { renderLogin(); return; } const pages = {dashboard, agents, 'agent-config': agentConfig, configs, tasks, settings, audit}; await (pages[state.route] || dashboard)(); } catch (error) { shell(`<section class="section"><div class="alert error">${esc(error.message)}</div></section>`, '错误'); } finally { state.busy = false; } }
window.addEventListener('hashchange', render);
render();
