import "./formatting_smoke.mjs";
import "./permissions_smoke.mjs";
import "./refresh_smoke.mjs";
import "./route_loader_smoke.mjs";
import "./requests_smoke.mjs";
import "./errors_smoke.mjs";
import "./core_logs_smoke.mjs";
import "./core_log_preferences_smoke.mjs";
import "./config_fields_smoke.mjs";
import "./access_control_smoke.mjs";
import "./system_bbr_smoke.mjs";
import "./config_files_smoke.mjs";
import "./config_outbounds_smoke.mjs";
import "./preset_drafts_smoke.mjs";
import "./preset_runtime_smoke.mjs";
import "./traffic_smoke.mjs";
import "./engine_capabilities_smoke.mjs";
import "./users_smoke.mjs";
import "./account_storage_smoke.mjs";
import "./node_order_smoke.mjs";
import "./panel_metrics_smoke.mjs";
import "./panel_reads_smoke.mjs";

// Await each domain suite: many install temporary DOM globals, and their
// setup/restore order is part of the regression contract.
const fixtures = {};
Object.assign(fixtures, await (await import("./smoke/helper-contracts.mjs")).run(fixtures));
Object.assign(fixtures, await (await import("./smoke/node-order.mjs")).run(fixtures));
Object.assign(fixtures, await (await import("./smoke/traffic-log-models.mjs")).run(fixtures));
Object.assign(fixtures, await (await import("./smoke/live-config-state.mjs")).run(fixtures));
Object.assign(fixtures, await (await import("./smoke/live-config-dual-source.mjs")).run(fixtures));
Object.assign(fixtures, await (await import("./smoke/live-config-unsupported.mjs")).run(fixtures));
Object.assign(fixtures, await (await import("./smoke/live-config-runtime.mjs")).run(fixtures));
Object.assign(fixtures, await (await import("./smoke/live-config-stale-runtime.mjs")).run(fixtures));
Object.assign(fixtures, await (await import("./smoke/installer-apis.mjs")).run(fixtures));
Object.assign(fixtures, await (await import("./smoke/deployment-recovery.mjs")).run(fixtures));
Object.assign(fixtures, await (await import("./smoke/agent-structure.mjs")).run(fixtures));
Object.assign(fixtures, await (await import("./smoke/code-format.mjs")).run(fixtures));
Object.assign(fixtures, await (await import("./smoke/latest-render.mjs")).run(fixtures));
Object.assign(fixtures, await (await import("./smoke/server-plan.mjs")).run(fixtures));
Object.assign(fixtures, await (await import("./smoke/card-drag.mjs")).run(fixtures));
Object.assign(fixtures, await (await import("./smoke/preset-workspace.mjs")).run(fixtures));
Object.assign(fixtures, await (await import("./smoke/route-data.mjs")).run(fixtures));
Object.assign(fixtures, await (await import("./smoke/client-access.mjs")).run(fixtures));
Object.assign(fixtures, await (await import("./smoke/substore.mjs")).run(fixtures));
Object.assign(fixtures, await (await import("./smoke/polling.mjs")).run(fixtures));
Object.assign(fixtures, await (await import("./smoke/preset-compaction.mjs")).run(fixtures));
Object.assign(fixtures, await (await import("./smoke/preset-forms.mjs")).run(fixtures));
Object.assign(fixtures, await (await import("./smoke/code-editor.mjs")).run(fixtures));
Object.assign(fixtures, await (await import("./smoke/archive-language.mjs")).run(fixtures));
Object.assign(fixtures, await (await import("./smoke/archive-readonly.mjs")).run(fixtures));
Object.assign(fixtures, await (await import("./smoke/public-addresses.mjs")).run(fixtures));
Object.assign(fixtures, await (await import("./smoke/public-address-runtime.mjs")).run(fixtures));
await import("./route_modules_smoke.mjs");
await import("./ip_quality_smoke.mjs");
