package api

import (
	"net/http"

	"github.com/qimaoww/qcontrolhub/internal/core"
)

func (s *Server) Handler() http.Handler {
	mux := http.NewServeMux()
	mux.HandleFunc("GET /healthz", s.health)
	mux.HandleFunc("GET /readyz", s.readiness)
	mux.HandleFunc("POST /api/v1/auth/login", s.login)
	mux.HandleFunc("GET /api/v1/auth/session", s.session)
	mux.HandleFunc("POST /api/v1/auth/logout", s.logout)
	mux.HandleFunc("GET /api/v1/agent-installer", s.serveAgentInstaller)

	mux.Handle("GET /api/v1/overview", s.requirePermission(core.PermissionOverviewRead, http.HandlerFunc(s.overview)))
	mux.Handle("GET /api/v1/panel-metrics", s.requirePermission(core.PermissionPanelMetricsRead, http.HandlerFunc(s.getPanelMetrics)))
	mux.Handle("GET /api/v1/agents", s.requirePermission(core.PermissionAgentsRead, http.HandlerFunc(s.listAgents)))
	mux.Handle("GET /api/v1/ip-quality", s.requirePermission(core.PermissionAgentsRead, http.HandlerFunc(s.ipQualityHistory)))
	mux.Handle("POST /api/v1/ip-quality", s.requireAllPermissions(
		[]core.Permission{core.PermissionAgentsManage, core.PermissionTasksExecute}, http.HandlerFunc(s.createIPQualityCheck)))
	mux.Handle("PUT /api/v1/ip-quality/schedules/{id}", s.requireAllPermissions(
		[]core.Permission{core.PermissionAgentsManage, core.PermissionTasksExecute}, http.HandlerFunc(s.putIPQualitySchedule)))
	mux.Handle("GET /api/v1/agent-access", s.requireAllPermissions(nil, http.HandlerFunc(s.getOwnAgentAccess)))
	mux.Handle("GET /api/v1/agent-directory", s.requirePermission(core.PermissionAgentsRead, http.HandlerFunc(s.listAgentDirectory)))
	mux.Handle("POST /api/v1/agent-access/{id}/response", s.requireAllPermissions(nil, http.HandlerFunc(s.respondAgentShare)))
	mux.Handle("GET /api/v1/deployments", s.requirePermission(core.PermissionDeploymentsRead, http.HandlerFunc(s.listDeployments)))
	mux.Handle("GET /api/v1/client-access", s.requirePermission(core.PermissionClientAccessRead, http.HandlerFunc(s.listClientAccess)))
	mux.Handle("GET /api/v1/substore-sync", s.requirePermission(core.PermissionClientAccessRead, http.HandlerFunc(s.getSubStoreSync)))
	mux.Handle("PUT /api/v1/substore-sync/settings", s.requirePermission(core.PermissionSettingsManage, http.HandlerFunc(s.putSubStoreSettings)))
	mux.Handle("POST /api/v1/substore-sync/targets", s.requirePermission(core.PermissionSettingsManage, s.subStoreMutation(s.createSubStoreTarget)))
	mux.Handle("GET /api/v1/substore-sync/remote-targets", s.requirePermission(core.PermissionSettingsManage, http.HandlerFunc(s.listSubStoreRemoteTargets)))
	mux.Handle("POST /api/v1/substore-sync/targets/import", s.requirePermission(core.PermissionSettingsManage, s.subStoreMutation(s.importSubStoreRemoteTarget)))
	mux.Handle("POST /api/v1/substore-sync/targets/{id}/remote", s.requirePermission(core.PermissionSettingsManage, s.subStoreMutation(s.linkSubStoreRemoteTarget)))
	mux.Handle("PUT /api/v1/substore-sync/targets/{id}", s.requirePermission(core.PermissionSettingsManage, s.subStoreMutation(s.updateSubStoreTarget)))
	mux.Handle("DELETE /api/v1/substore-sync/targets/{id}", s.requirePermission(core.PermissionSettingsManage, s.subStoreMutation(s.deleteSubStoreTarget)))
	mux.Handle("PUT /api/v1/substore-sync/selections", s.requirePermission(core.PermissionSettingsManage, s.subStoreMutation(s.putSubStoreSelections)))
	mux.Handle("POST /api/v1/substore-sync/test", s.requirePermission(core.PermissionSettingsManage, http.HandlerFunc(s.testSubStoreConnection)))
	mux.Handle("POST /api/v1/substore-sync/run", s.requirePermission(core.PermissionSettingsManage, s.subStoreMutation(s.runSubStoreSync)))
	mux.Handle("GET /api/v1/core-logs", s.requirePermission(core.PermissionCoreLogsRead, http.HandlerFunc(s.listCoreLogs)))
	mux.Handle("GET /api/v1/access-controls", s.requirePermission(core.PermissionAgentConfigRead, http.HandlerFunc(s.listMainlandAccessPolicies)))
	mux.Handle("PUT /api/v1/access-controls", s.requireAllPermissions(
		[]core.Permission{core.PermissionAgentConfigWrite, core.PermissionTasksExecute},
		http.HandlerFunc(s.putMainlandAccessPolicy),
	))
	mux.Handle("PUT /api/v1/agents/{id}/client-address", s.requirePermission(core.PermissionAgentsManage, http.HandlerFunc(s.putAgentClientAddress)))
	mux.Handle("GET /api/v1/agents/{id}/region", s.requirePermission(core.PermissionAgentsRead, http.HandlerFunc(s.getAgentRegion)))
	mux.Handle("PUT /api/v1/agents/{id}/region", s.requirePermission(core.PermissionAgentsManage, http.HandlerFunc(s.putAgentRegion)))
	mux.Handle("GET /api/v1/regions", s.requirePermission(core.PermissionAgentsRead, http.HandlerFunc(s.listRegions)))
	mux.Handle("GET /api/v1/region-flags/{code}", s.requirePermission(core.PermissionAgentsRead, http.HandlerFunc(s.getRegionFlag)))
	mux.Handle("GET /api/v1/agents/{id}/komari", s.requirePermission(core.PermissionAgentsRead, http.HandlerFunc(s.getAgentKomari)))
	mux.Handle("PUT /api/v1/agents/{id}/komari", s.requirePermission(core.PermissionAgentsManage, http.HandlerFunc(s.putAgentKomari)))
	mux.Handle("PUT /api/v1/agents/{id}/name", s.requirePermission(core.PermissionAgentsManage, http.HandlerFunc(s.putAgentName)))
	mux.Handle("PUT /api/v1/agents/{id}/visibility", s.requirePermission(core.PermissionAgentsManage, http.HandlerFunc(s.putAgentVisibility)))
	mux.Handle("GET /api/v1/agents/{id}/sharing", s.requirePermission(core.PermissionAgentsManage, http.HandlerFunc(s.getAgentSharing)))
	mux.Handle("PUT /api/v1/agents/{id}/sharing", s.requirePermission(core.PermissionAgentsManage, http.HandlerFunc(s.putAgentSharing)))
	mux.Handle("PUT /api/v1/agents/{id}/capabilities/{engine}", s.requirePermission(core.PermissionAgentsManage, http.HandlerFunc(s.putAgentEngineCapability)))
	mux.Handle("GET /api/v1/config-catalogs/{engine}", s.requirePermission(core.PermissionCatalogsRead, http.HandlerFunc(s.configCatalog)))
	mux.Handle("DELETE /api/v1/agents/{id}", s.requirePermission(core.PermissionAgentsManage, http.HandlerFunc(s.deleteAgent)))
	mux.Handle("POST /api/v1/agents/{id}/enrollment-token", s.requirePermission(core.PermissionEnrollmentManage, http.HandlerFunc(s.createAgentEnrollmentToken)))
	mux.Handle("POST /api/v1/agents/{id}/enrollment-command", s.requirePermission(core.PermissionEnrollmentManage, http.HandlerFunc(s.getAgentEnrollmentCommand)))
	mux.Handle("GET /api/v1/agents/{id}/configs", s.requirePermission(core.PermissionAgentConfigRead, http.HandlerFunc(s.listAgentConfigs)))
	mux.Handle("GET /api/v1/agents/{id}/configs/{engine}", s.requirePermission(core.PermissionAgentConfigRead, http.HandlerFunc(s.getAgentConfig)))
	mux.Handle("PUT /api/v1/agents/{id}/configs/{engine}", s.requirePermission(core.PermissionAgentConfigWrite, http.HandlerFunc(s.putAgentConfig)))
	mux.Handle("GET /api/v1/agents/{id}/configs/{engine}/files", s.requirePermission(core.PermissionAgentConfigRead, http.HandlerFunc(s.getAgentConfigFiles)))
	mux.Handle("PUT /api/v1/agents/{id}/configs/{engine}/files", s.requirePermission(core.PermissionAgentConfigWrite, http.HandlerFunc(s.putAgentConfigFiles)))
	mux.Handle("GET /api/v1/agents/{id}/configs/{engine}/workspace", s.requirePermission(core.PermissionAgentConfigRead, http.HandlerFunc(s.agentConfigWorkspace)))
	mux.Handle("POST /api/v1/agents/{id}/configs/{engine}/plans", s.requirePermission(core.PermissionAgentConfigWrite, http.HandlerFunc(s.newServerPlan)))
	mux.Handle("POST /api/v1/agents/{id}/configs/{engine}/server-inbounds", s.requireAllPermissions([]core.Permission{core.PermissionAgentConfigWrite, core.PermissionTasksExecute}, http.HandlerFunc(s.saveServerInbound)))
	mux.Handle("GET /api/v1/agents/{id}/configs/{engine}/fields/{key}", s.requirePermission(core.PermissionAgentConfigRead, http.HandlerFunc(s.getConfigField)))
	mux.Handle("POST /api/v1/agents/{id}/configs/{engine}/fields/{key}", s.requireAllPermissions([]core.Permission{core.PermissionAgentConfigWrite, core.PermissionTasksExecute}, http.HandlerFunc(s.saveConfigField)))
	mux.Handle("POST /api/v1/agents/{id}/configs/{engine}/source", s.requireAllPermissions([]core.Permission{core.PermissionAgentConfigWrite, core.PermissionTasksExecute}, http.HandlerFunc(s.savePresetSource)))
	mux.Handle("GET /api/v1/configs", s.requirePermission(core.PermissionConfigsRead, http.HandlerFunc(s.listConfigs)))
	mux.Handle("POST /api/v1/configs", s.requirePermission(core.PermissionConfigsWrite, http.HandlerFunc(s.createConfig)))
	mux.Handle("PUT /api/v1/configs/{id}", s.requirePermission(core.PermissionConfigsWrite, http.HandlerFunc(s.updateConfig)))
	mux.Handle("DELETE /api/v1/configs/{id}", s.requirePermission(core.PermissionConfigsDelete, http.HandlerFunc(s.deleteConfig)))
	mux.Handle("GET /api/v1/configs/{id}/revisions", s.requirePermission(core.PermissionConfigsRead, http.HandlerFunc(s.listConfigRevisions)))
	mux.Handle("GET /api/v1/configs/{id}/revisions/{version}", s.requirePermission(core.PermissionConfigsRead, http.HandlerFunc(s.getConfigRevision)))
	mux.Handle("POST /api/v1/configs/{id}/revisions/{version}/restore", s.requirePermission(core.PermissionConfigsRestore, http.HandlerFunc(s.restoreConfigRevision)))
	mux.Handle("GET /api/v1/tasks", s.requirePermission(core.PermissionTasksRead, http.HandlerFunc(s.listTasks)))
	mux.Handle("GET /api/v1/system-tcp/tasks", s.requirePermission(core.PermissionTasksRead, http.HandlerFunc(s.latestSystemTCPTasks)))
	mux.Handle("GET /api/v1/system-tcp/parameters", s.requirePermission(core.PermissionAgentsRead, http.HandlerFunc(func(w http.ResponseWriter, request *http.Request) {
		writeJSON(w, http.StatusOK, core.TCPParameterRules())
	})))
	mux.Handle("POST /api/v1/tasks", s.requirePermission(core.PermissionTasksExecute, http.HandlerFunc(s.createTask)))
	mux.Handle("GET /api/v1/tasks/{id}", s.requirePermission(core.PermissionTasksRead, http.HandlerFunc(s.getTask)))
	mux.Handle("GET /api/v1/tasks/{id}/config-snapshot", s.requireAllPermissions(
		[]core.Permission{core.PermissionTasksRead, core.PermissionAgentConfigRead},
		http.HandlerFunc(s.getTaskConfigSnapshot),
	))
	mux.Handle("DELETE /api/v1/tasks/{id}", s.requirePermission(core.PermissionTasksExecute, http.HandlerFunc(s.cancelTask)))
	mux.Handle("POST /api/v1/tasks/{id}/retry", s.requirePermission(core.PermissionTasksExecute, http.HandlerFunc(s.retryTask)))
	mux.Handle("GET /api/v1/enrollment-tokens", s.requirePermission(core.PermissionEnrollmentManage, http.HandlerFunc(s.listEnrollmentTokens)))
	mux.Handle("POST /api/v1/enrollment-tokens", s.requirePermission(core.PermissionEnrollmentManage, http.HandlerFunc(s.createEnrollmentToken)))
	mux.Handle("DELETE /api/v1/enrollment-tokens/{id}", s.requirePermission(core.PermissionEnrollmentManage, http.HandlerFunc(s.deleteEnrollmentToken)))
	mux.Handle("POST /api/v1/enrollment-tokens/{id}/command", s.requirePermission(core.PermissionEnrollmentManage, http.HandlerFunc(s.getEnrollmentCommand)))
	mux.Handle("GET /api/v1/settings", s.requirePermission(core.PermissionSettingsRead, http.HandlerFunc(s.getSettings)))
	mux.Handle("PUT /api/v1/settings", s.requirePermission(core.PermissionSettingsManage, http.HandlerFunc(s.putSettings)))
	mux.Handle("GET /api/v1/settings/deployment", s.requirePermission(core.PermissionSettingsRead, http.HandlerFunc(s.getDeploymentSettings)))
	mux.Handle("POST /api/v1/settings/check-update", s.requirePermission(core.PermissionSettingsRead, http.HandlerFunc(s.checkUpdate)))
	mux.Handle("GET /api/v1/audit", s.requirePermission(core.PermissionAuditRead, http.HandlerFunc(s.listAudit)))
	mux.Handle("GET /api/v1/users", s.requirePermission(core.PermissionUsersManage, http.HandlerFunc(s.listUsers)))
	mux.Handle("POST /api/v1/users", s.requirePermission(core.PermissionUsersManage, http.HandlerFunc(s.createUser)))
	mux.Handle("PUT /api/v1/users/{id}", s.requirePermission(core.PermissionUsersManage, http.HandlerFunc(s.updateUser)))
	mux.Handle("DELETE /api/v1/users/{id}", s.requirePermission(core.PermissionUsersManage, http.HandlerFunc(s.deleteUser)))
	mux.Handle("POST /api/v1/users/{id}/purge", s.requirePermission(core.PermissionUsersManage, http.HandlerFunc(s.purgeUser)))
	mux.Handle("GET /api/v1/users/{id}/agent-access", s.requirePermission(core.PermissionUsersManage, http.HandlerFunc(s.getUserAgentAccess)))
	mux.Handle("PUT /api/v1/users/{id}/agent-access", s.requirePermission(core.PermissionUsersManage, http.HandlerFunc(s.putUserAgentAccess)))
	mux.Handle("GET /api/v1/metrics/{id}", s.requirePermission(core.PermissionMetricsRead, http.HandlerFunc(s.metricSamples)))
	mux.Handle("GET /api/v1/traffic-policies", s.requirePermission(core.PermissionTrafficRead, http.HandlerFunc(s.listPortTrafficPolicies)))
	mux.Handle("GET /api/v1/traffic-endpoints", s.requirePermission(core.PermissionTrafficRead, http.HandlerFunc(s.listPortTrafficEndpoints)))
	mux.Handle("POST /api/v1/traffic-endpoints/sync", s.requirePermission(core.PermissionTrafficManage, http.HandlerFunc(s.syncPortTrafficEndpoints)))
	mux.Handle("GET /api/v1/traffic-endpoints/sync", s.requirePermission(core.PermissionTrafficManage, http.HandlerFunc(s.previewPortTrafficSync)))
	mux.Handle("GET /api/v1/traffic-usage", s.requirePermission(core.PermissionTrafficRead, http.HandlerFunc(s.listPortTrafficUsage)))
	mux.Handle("POST /api/v1/traffic-policies", s.requirePermission(core.PermissionTrafficManage, http.HandlerFunc(s.createPortTrafficPolicy)))
	mux.Handle("PUT /api/v1/traffic-policies/{id}", s.requirePermission(core.PermissionTrafficManage, http.HandlerFunc(s.updatePortTrafficPolicy)))
	mux.Handle("POST /api/v1/traffic-policies/{id}/reset", s.requirePermission(core.PermissionTrafficManage, http.HandlerFunc(s.resetPortTrafficPolicy)))
	mux.Handle("DELETE /api/v1/traffic-policies/{id}", s.requirePermission(core.PermissionTrafficManage, http.HandlerFunc(s.deletePortTrafficPolicy)))
	mux.Handle("DELETE /api/v1/traffic-policies/{id}/monitoring", s.requirePermission(core.PermissionTrafficManage, http.HandlerFunc(s.deletePortTrafficMonitoring)))
	mux.Handle("GET /api/v1/templates", s.requirePermission(core.PermissionTemplatesRead, http.HandlerFunc(s.listTemplates)))
	mux.Handle("POST /api/v1/templates", s.requirePermission(core.PermissionTemplatesWrite, http.HandlerFunc(s.createTemplate)))
	mux.Handle("DELETE /api/v1/templates/{id}", s.requirePermission(core.PermissionTemplatesDelete, http.HandlerFunc(s.deleteTemplate)))
	mux.Handle("POST /api/v1/templates/{id}/apply", s.requireAllPermissions(
		[]core.Permission{core.PermissionTemplatesWrite, core.PermissionAgentConfigWrite},
		http.HandlerFunc(s.applyTemplate),
	))

	mux.HandleFunc("GET /api/v1/agent-binary", s.serveAgentBinary)
	mux.Handle("GET /agent/v1/binary", s.agent(http.HandlerFunc(s.serveAgentBinaryForAgent)))

	mux.HandleFunc("POST /agent/v1/enroll", s.enrollAgent)
	mux.Handle("GET /agent/v1/connect", s.agent(http.HandlerFunc(s.agentConnect)))

	return s.middleware(mux)
}
