package serverconfig

import (
	"encoding/json"
	"fmt"
	"strings"

	"github.com/qimaoww/qcontrolhub/internal/configschema"
	"github.com/qimaoww/qcontrolhub/internal/core"
)

// Identity checks and list selection must be symmetric: an inbound cannot
// collide with an endpoint, and an endpoint cannot collide with an inbound.
func singBoxGeneratedEntry(content string) (SingBoxEntry, error) {
	entries, err := DiscoverSingBoxEntries(content)
	if err != nil {
		return SingBoxEntry{}, err
	}
	if len(entries) != 1 {
		return SingBoxEntry{}, fmt.Errorf("generated sing-box configuration must contain exactly one inbound or endpoint")
	}
	return entries[0], nil
}

func mergeSingBoxGenerated(content, generated string) (string, error) {
	if strings.TrimSpace(content) == "" {
		content = "{}"
	}
	candidate, err := singBoxGeneratedEntry(generated)
	if err != nil {
		return "", err
	}
	entries, err := DiscoverSingBoxEntries(content)
	if err != nil {
		return "", err
	}
	for _, entry := range entries {
		if entry.Tag == candidate.Tag {
			return mutateSingBoxGenerated(content, generated, entry.Tag, "modify")
		}
	}
	// Preserve legacy primary-entry replacement, but never cross native lists.
	for _, input := range ParseAll(core.EngineSingBox, content) {
		protocol, ok := FindProtocol(core.EngineSingBox, input.Protocol)
		if ok && protocol.UsesEndpoint == (candidate.Section == "endpoints") {
			return mutateSingBoxGenerated(content, generated, input.Tag, "modify")
		}
	}
	return mutateSingBoxGenerated(content, generated, "", "add")
}

func deleteSingBoxPresetEntry(content, tag string) (string, error) {
	entries, err := DiscoverSingBoxEntries(content)
	if err != nil {
		return "", err
	}
	for _, entry := range entries {
		if entry.Tag != tag {
			continue
		}
		if err := ValidateSingBoxEntryIdentity(content, entry, tag, "delete"); err != nil {
			return "", err
		}
		// No credentials, protocol fields or draft port are needed to delete.
		generated, _ := json.Marshal(map[string]any{entry.Section: []any{map[string]any{"tag": tag}}})
		return configschema.MutateListItem(core.EngineSingBox, content, string(generated), entry.Section, "tag", tag, "delete")
	}
	return "", fmt.Errorf("sing-box entry %q does not exist", tag)
}

func mutateSingBoxGenerated(content, generated, originalTag, operation string) (string, error) {
	if strings.TrimSpace(content) == "" {
		content = "{}"
	}
	if operation == "delete" {
		return deleteSingBoxPresetEntry(content, originalTag)
	}
	candidate, err := singBoxGeneratedEntry(generated)
	if err != nil {
		return "", err
	}
	if err := ValidateSingBoxEntryIdentity(content, candidate, originalTag, operation); err != nil {
		return "", err
	}
	keys := []string{
		"tag", "listen", "listen_port", "type", "method", "password", "users", "up_mbps", "down_mbps",
		"congestion_control", "auth_timeout", "heartbeat", "tls", "transport", "network", "override_address", "override_port",
	}
	if candidate.Section == "endpoints" {
		if _, ok := parseSingBoxEndpoint(generated); !ok {
			return "", fmt.Errorf("sing-box endpoint cannot be safely generated by this preset")
		}
		if operation == "modify" {
			var root map[string]any
			if err := json.Unmarshal([]byte(content), &root); err != nil {
				return "", err
			}
			entries, _ := root["endpoints"].([]any)
			for _, raw := range entries {
				entry := mapValue(raw)
				if entry["tag"] == originalTag {
					if _, ok := parseSingBoxEndpointProtocol(entry); !ok {
						return "", fmt.Errorf("sing-box endpoint %q contains custom fields or unsupported peers; use the full source editor", originalTag)
					}
				}
			}
		}
		keys = []string{"type", "tag", "system", "mtu", "address", "private_key", "listen_port", "peers"}
	}
	merged, err := configschema.MutateListItem(core.EngineSingBox, content, generated, candidate.Section, "tag", originalTag, operation, keys...)
	if err != nil {
		return "", err
	}
	return enforceCentralLogging(core.EngineSingBox, merged)
}
