package serverconfig

import (
	"crypto/ecdh"
	"encoding/base64"
	"encoding/json"

	"github.com/qimaoww/qcontrolhub/internal/core"
	"gopkg.in/yaml.v3"
)

// Parse reads configurations generated by this package back into the server
// inbound form. Arbitrary configurations simply return ok=false and remain
// available through the advanced source editor.
func Parse(engine core.Engine, content string) (input Input, ok bool) {
	switch engine {
	case core.EngineMihomo:
		return parseMihomo(content)
	case core.EngineXray:
		return parseXray(content)
	case core.EngineSingBox:
		return parseSingBox(content)
	case core.EngineShadowsocksRust:
		return parseShadowsocksRust(content)
	default:
		return Input{}, false
	}
}

// ParseAll returns every supported generated-style inbound in document order.
// Unsupported/custom inbounds remain untouched by mutation operations and are
// still available through the full source editor.
func ParseAll(engine core.Engine, content string) []Input {
	if engine == core.EngineShadowsocksRust {
		var root map[string]any
		if json.Unmarshal([]byte(content), &root) != nil || root == nil {
			return nil
		}
		if input, ok := parseShadowsocksRustEntry(root, "ss-rust"); ok {
			return []Input{input}
		}
		_, entries, ok := shadowsocksRustExtendedEntries(root)
		if !ok {
			return nil
		}
		result := make([]Input, 0, len(entries))
		for index, value := range entries {
			entry := mapValue(value)
			if input, ok := parseShadowsocksRustEntry(entry, shadowsocksRustEntryTag(entry, index)); ok {
				result = append(result, input)
			}
		}
		return result
	}
	var root map[string]any
	listKey := "inbounds"
	protocolField := "protocol"
	if engine == core.EngineMihomo {
		listKey, protocolField = "listeners", "type"
		if yaml.Unmarshal([]byte(content), &root) != nil {
			return nil
		}
	} else {
		if json.Unmarshal([]byte(content), &root) != nil {
			return nil
		}
		if engine == core.EngineSingBox {
			protocolField = "type"
		}
	}
	items, _ := root[listKey].([]any)
	result := make([]Input, 0, len(items))
	for _, item := range items {
		candidate := mapValue(item)
		protocol := protocolKey(stringValue(candidate[protocolField]))
		if _, ok := FindProtocol(engine, protocol); !ok {
			continue
		}
		single := map[string]any{listKey: []any{candidate}}
		var encoded []byte
		var err error
		if engine == core.EngineMihomo {
			encoded, err = yaml.Marshal(single)
		} else {
			encoded, err = json.Marshal(single)
		}
		if err != nil {
			continue
		}
		if parsed, ok := Parse(engine, string(encoded)); ok {
			result = append(result, parsed)
		}
	}
	return result
}

func stringValue(value any) string {
	result, _ := value.(string)
	return result
}

func intValue(value any) int {
	switch typed := value.(type) {
	case int:
		return typed
	case int64:
		return int(typed)
	case float64:
		return int(typed)
	default:
		return 0
	}
}

func mapValue(value any) map[string]any {
	result, _ := value.(map[string]any)
	return result
}

func firstMap(value any) map[string]any {
	items, _ := value.([]any)
	if len(items) == 0 {
		return nil
	}
	return mapValue(items[0])
}

func firstSupportedInbound(engine core.Engine, value any, protocolField string) map[string]any {
	items, _ := value.([]any)
	for _, item := range items {
		candidate := mapValue(item)
		protocol := protocolKey(stringValue(candidate[protocolField]))
		if _, ok := FindProtocol(engine, protocol); ok {
			return candidate
		}
	}
	return nil
}

func firstString(value any) string {
	items, _ := value.([]any)
	if len(items) == 0 {
		if strings, ok := value.([]string); ok && len(strings) > 0 {
			return strings[0]
		}
		return ""
	}
	return stringValue(items[0])
}

func realityPublicKey(privateValue string) string {
	privateBytes, err := base64.RawURLEncoding.DecodeString(privateValue)
	if err != nil {
		return ""
	}
	privateKey, err := ecdh.X25519().NewPrivateKey(privateBytes)
	if err != nil {
		return ""
	}
	return base64.RawURLEncoding.EncodeToString(privateKey.PublicKey().Bytes())
}

func protocolKey(value string) string {
	switch value {
	case "shadowsocks":
		return ProtocolSS2022
	case "vless":
		return ProtocolVLESS
	case "vmess":
		return ProtocolVMess
	case "trojan":
		return ProtocolTrojan
	case "hysteria", "hysteria2":
		return ProtocolHy2
	case "tuic":
		return ProtocolTUIC
	case "anytls":
		return ProtocolAnyTLS
	default:
		return ""
	}
}
